### ISSUE TITLE
Can't get modal view to work

### ISSUE THREAD

**Issue by seifsallam** [Semantic-Org/Semantic-UI-Ember#10]
I've followed the README docs for the setup, but the modal template doesn't get displayed. The template itself does get inserted into DOM, but nothing appears. Is there anything i'm missing here?

**Comment by nathanpalmer** [comment]
@seifsallam Looks like the documentation does need to be updated slightly. Are you using a View along with the template? (it's optional.) However if you are the syntax should look more like this

```javascript
import Ember from 'ember';
import SemanticModalMixin from 'semantic-ui-ember/mixins/modal';

export default Ember.View.extend(SemanticModalMixin, {
  templateName: 'shared/modal'
});
```

**Comment by seifsallam** [comment]
Thanks, also i found that route configuration is wrong. It should be

```js
import SemanticRouteMixin from 'semantic-ui-ember/mixins/application-route';
// instead of
import SemanticModalMixin from 'semantic-ui-ember/mixins/modal';
```

**Comment by nathanpalmer** [comment]
Great! The README has also been updated.
