### ISSUE TITLE
Not compatible with Ember fastboot

### ISSUE THREAD

**Issue by ewoutp** [Semantic-Org/Semantic-UI-Ember#100]
When trying ember-fastboot on a site that uses semantic-ui, I get all kinds of compile errors regarding missing `jQuery` and `document` variables.

Being compatible with fastboot would be REALLY welcome.

**Comment by aaronbhansen** [comment]
Thanks, we are actively working on the 2.0 release, then we'll look at ember fastboot next.

**Comment by ewoutp** [comment]
👍 

When you need a tester, please let me know.

**Comment by matbox** [comment]
Is there an update on this one (I guess I'm just hoping someone is taking it on and saves me the hacking ;-))

**Comment by aaronbhansen** [comment]
It will probably be a few months honestly. Unless someone else wants to start a pull request.

**Comment by ewoutp** [comment]
Fastboot has now documented how to fix issues like this. See https://github.com/ember-fastboot/ember-cli-fastboot/issues/134#issuecomment-197540068

**Comment by Panman8201** [comment]
Latest-n-greatest documentation/guide: http://ember-fastboot.com/docs/addon-author-guide

**Comment by matbox** [comment]
Any update on the progress?

**Comment by aaronbhansen** [comment]
I don't have any plans to tackle this in the near future. Anyone that wants the feature is free to do the work and submit a PR.

**Comment by nahtnam** [comment]
@davidpett has made #184
