### ISSUE TITLE
How do ui-dropdown work with not string variables?

### ISSUE THREAD

**Issue by kaermorchen** [Semantic-Org/Semantic-UI-Ember#101]
Hello.

I can't figure out how to work the ui-dropdown.

```
# controllers/index.js
 sexs: [
    Ember.Object.create({name: "Not pick", value: null}),
    Ember.Object.create({name: "Man", value: true}),
    Ember.Object.create({name: "Woman", value: false})
  ],
  actions: {
    setSex: function (component, id, value) {
      console.log(component, id, value);      
      this.set('model.sex', value);
    }
}
```
```
# templates/index.hbs
{{#ui-dropdown class="selection" disabled=isNotEditable onChange=(action 'setSex')}}
	<i class="dropdown icon"></i>

	{{#if (eq model.sex true)}}<div class="default text">Man</div>{{/if}}
	{{#if (eq model.sex false)}}<div class="default text">Woman</div>{{/if}}
	{{#if (eq model.sex null)}}<div class="default text">Not pick</div>{{/if}}

	<div class="menu">
		{{#each sexs as |sex|}}
			<div class="item" data-value={{sex.value}}>{{sex.name}}</div>
		{{/each}}
	</div>
{{/ui-dropdown}}
```

When I change dropdown I see in console
```
Class {...} "true" "Man"
Class {...} "false" "Woman"
Class {...} "not pick" "Not pick"
```

How better to do to get true, false and null?

**Comment by aaronbhansen** [comment]
ui-dropdown used to allow value binding (in Semantic-UI), then it was changed to only allow string binding to better align with html. Because of this, we created a new dropdown called UI-Dropdown-Array. That will let you bind to an object. I'll add a ticket to update the readme, but you can look at the [example](https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/tests/dummy/app/templates/modules/dropdown.hbs) in the dummy app.

**Comment by kaermorchen** [comment]
@aaronbhansen thanks for the reply, but as far as I understand, ui-dropdown-array will return a whole object, not on a specific value? How do I use ui-dropdown-array?

**Comment by aaronbhansen** [comment]
Ah I thought you wanted the whole object. We use value binding for most of our dropdowns today. Here is the example of our country dropdown

```
    {{#ui-dropdown class="fluid selection" selected=card.country}}
      <input type="hidden" name="country" value={{card.country}}>
      <i class="dropdown icon"></i>
      <div class="default text"></div>
      <div class="menu">
      {{#each countries as |content|}}
        <div class="item" data-value={{content.iso3}}>{{content.name}}</div>
      {{/each}}
      </div>
    {{/ui-dropdown}}
```

With your action binding though, if you look at the semantic documentation, it should pass the value into the action and you can parse it from there on the standard dropdown. As I mentioned in my first comment, everything is a string to semantic, so even though you have true as the data value, you would need to parse it back to false in your action. We are looking at possibly adding some transformers in the 2.0 branch to convert the string back to a boolean for example in the action, but nothing definite yet. 

I'd say for now your best approach is to do something like

```
setSex(component, value, text) {
  if (value === "true") {
    this.set('property', true); 
 }
 ...
}
```
