### ISSUE TITLE
Icon files have the wrong path and are not found (404)

### ISSUE THREAD

**Issue by cwilli34** [Semantic-Org/Semantic-UI-Ember#104]
`Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:4200/themes/default/assets/fonts/icons.woff Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:4200/themes/default/assets/fonts/icons.ttf Failed to load resource: the server responded with a status of 404 (Not Found)`

Icons are not showing.  I have my set up with LESS support, an app.less and theme.less file, and a theme.config file.

**Comment by aaronbhansen** [comment]
I haven't seen this issue personally. Do you have the ember security policy and if so did you whitelist those file types?

**Comment by cwilli34** [comment]
I don't anything about the ember security policy and I haven't whitelisted any file types.  So I am not sure.  But the actual path should be `assets/themes/default/assets/fonts/icons.woff`, etc.  It is leaving out the assets part of the path.  Actually I don't know if that is the correct path either, but in my dist directory, that would be the path created by broccoli.

**Comment by aaronbhansen** [comment]
You could try importing your theme or files directly. Not entirely sure what the problem is, so throwing out ideas.

ember-cli-build.js
```

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
  
  app.import({
    development: 'bower_components/semantic-ui/dist/semantic.css',
    production: 'bower_components/semantic-ui/dist/semantic.min.css'
  });

  ...
```

**Comment by cwilli34** [comment]
```
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {

  app.import({
    development: 'bower_components/semantic-ui/dist/semantic.css',
    production: 'bower_components/semantic-ui/dist/semantic.min.css'
  });
```
So this does work, however I still get the errors:

![screenshot_20160519_101755](https://cloud.githubusercontent.com/assets/9610352/15396669/14f9cb7a-1dab-11e6-9bbc-15b0823a6a3c.png)

This doesn't fix the issue.  So it might have something to do with my LESS options.  Instead of app.css I have app.less, and in ember-cli-build.js I have:

```
var app = new EmberApp(defaults, {
        lessOptions: {
            paths: [
                'bower_components/semantic-ui'
            ]
        },

        SemanticUI: {
            css: false,
            javascript: true,
            fonts: true
        }
    });

    app.import({
        development: 'bower_components/semantic-ui/dist/semantic.css',
        production: 'bower_components/semantic-ui/dist/semantic.min.css'
    });
```

And I have installed ember-cli-less through npm.  I have a theme.config in the root, and app.less and theme.less in the styles folder in the app directory.  Am I missing something? The font files are actually in `dist/assets/themes/default/assets/fonts/` when the ember server is started.

**Comment by aaronbhansen** [comment]
Unfortunately I'm not sure where to go with this at the moment. If you can create an Ember twiddle or demo project replicating the issue we can look at it more. It's hard to know if its something in your app specifically or semantic without having a demo to look at.

**Comment by jcano** [comment]
I'm also having this issue and I had it before with other addons. In my case the problem comes with changing `outputPaths` on ember-cli-build.js. By default, many addons expect to find all the files directly under `assets/` and if the files are somewhere else they will fail to import.  My config looks like this:

```js
var app = new EmberApp(defaults, {
    // Add options here
    outputPaths: {
      app: {
        css: {
          app: "/assets/css/ember-webapp.css",
        },
        js: "/assets/js/ember-webapp.js",
      },

      vendor: {
        css: "/assets/css/vendor.css",
        js: "/assets/js/vendor.js",
      },
    },
  });
```

In this case, it is the semantic-ui bower component that requires a specific file structure, it loads the fonts like this:

```scss
src: url("themes/default/assets/fonts/icons.eot");
src: url("themes/default/assets/fonts/icons.eot?#iefix") format('embedded-opentype'),
    url("themes/default/assets/fonts/icons.woff2") format('woff2'),
    url("themes/default/assets/fonts/icons.woff") format('woff'),
    url("themes/default/assets/fonts/icons.ttf") format('truetype'),
    url("themes/default/assets/fonts/icons.svg#icons") format('svg');
```

All paths assume that the `themes` directory will be on the same directory as the css file so in my case it would be `assets/css/themes`. I managed to solve this issue by changing the main `index.js` like this:

```js
if (getWithDefault(options['fonts'], defaults['fonts'])) {
  var fontExtensions = ['.eot','.otf','.svg','.ttf','.woff','.woff2'];
  var fontOptions = { destDir: 'assets/css/themes/default/assets/fonts' };
  for (var i = fontExtensions.length - 1; i >= 0; i--) {
    app.import('bower_components/semantic-ui/dist/themes/default/assets/fonts/icons'+fontExtensions[i], fontOptions);
  };
}
```

Specifically, I changed the `fontOptions` to `{ destDir: 'assets/css/themes/default/assets/fonts' }`. The general solution would be to let the user pass the path to the fonts (and images). At the beginning of `index.js` you get the options like this:

```js
var options = (app && app.options['SemanticUI']) || {};
```
So letting the user add a `cssPath` or `cssRoot` in the options and loading the themes directory on that path (for example `{ destDir: options.cssPath + 'themes/default/assets/fonts' }`) would fix the issue.

@cwilli34 Could you try editing `node_modules/semantic-ui-ember/index.js` and change the `fontOptions` to where ember is copying your css? This should solve your problem, if not it must be some other configuration option clashing. Check were ember is copying both, the css and semantic's `themes` directory.

@aaronbhansen If you think this is a good solution, I can submit a pull request later today with those changes.

**Comment by cwilli34** [comment]
> @cwilli34 Could you try editing node_modules/semantic-ui-ember/index.js and change the fontOptions to where ember is copying your css? This should solve your problem, if not it must be some other configuration option clashing. Check were ember is copying both, the css and semantic's themes directory.

This doesn't change anything.  I still get the same errors.  I put `assets/css/themes/default/assets/images` and `assets/css/themes/default/assets/fonts` in the index.js in the node modules/semantic-ui/ directory and I still get the same exact error.

This error is mentioned by @jayphelps in #7, in which @nathanpalmer said it is fixed with updates of semantic-ui-ember and jQuery, but it obviously is not because I have cloned the [example](https://github.com/nathanpalmer/example-semantic-ui-ember-cli/commits/master) here and ran the ember server and still receive the exact same errors.

This may have something to do with trying to use ember-cli-less and semantic-ui-ember and not having the correct lessOptions.  I am not sure.  But @aaronbhansen, if you clone the example by @nathanpalmer  in the link I just posted, install it, add a icon to the button in his example, and then run the ember server, you will get the same errors that I am posting here when you try to click on where the icon should be.

**Comment by jcano** [comment]
@cwilli34 When using `ember serve`, where does your vendor.css go? Can you share you dist directory structure? I'm not familiar with ember-cli-less, but it might not copy the output css to a standard path.

**Comment by cwilli34** [comment]
@jcano It was putting my vendor.css file and my app.css file straight into the assets folder in /dist, but I went ahead and also tried doing what you had done: 

> ```
var app = new EmberApp(defaults, {
    // Add options here
    outputPaths: {
      app: {
        css: {
          app: "/assets/css/ember-webapp.css",
        },
        js: "/assets/js/ember-webapp.js",
      },
      vendor: {
        css: "/assets/css/vendor.css",
        js: "/assets/js/vendor.js",
      },
    },
  });
```
and my directory structure did change to having /css and /js folders inside the assets directory.  Of course I also had to change my index.html file in my app directory to reflect those changes. The font files are located in `assets/css/themes/default/assets/fonts/` but no matter what I changed, I couldn't seem to get ember to look there.  Same error: `http://localhost:4200/themes/default/assets/fonts/`.  I went as far as making the same changes to the `index.js` file in `node_modules/semantic-ui` that you have made, and added the `cssPath: 'assets/css'` option to my ember-cli-build.js, and it didn't change a thing.

UPDATE: So I finally found the issue.  In the themes directory located in `node_modules/semantic-ui/src/themes` there are two files (the one in default is the most concerning) named `site.variables` in both the `default/globals` directory and the `flat/globals` directory that have "hard-coded" paths to the themes file.  `@imagePath` is set as `../../themes/default/assets/images` and `@fontPath` is set as `../../themes/default/assets/fonts`.  This is making it so that the semantic.min.css file is looking directly for those paths.  I removed the `../../` from all the paths, and kept the changes that @jcano has posted in #108, and everything works smoothly now.  I am using custom `themes` and `site` directories copied to my `styles` directory, so I did have to change the themes.config paths for `@themesFolder` to `app/styles/themes` and `@siteFolder` to `app/styles/site`.  So this is now my configuration in ember-cli-build.js:

```
module.exports = function (defaults) {
    var app = new EmberApp(defaults, {
        lessOptions: {
            paths: [
                'bower_components/semantic-ui'
            ]
        },
        outputPaths: {
            app: {
                css: {
                    app: "assets/css/ember-osf-dashboard.css"
                },
                js: "assets/js/ember-osf-dashboard.js"
            },
            vendor: {
                css: "assets/css/vendor.css",
                js: "assets/js/vendor.js"
            }
        },
        SemanticUI: {
            css: false,
            javascript: true,
            fonts: true,
            cssPath: "assets/css"
        },
    });
```

This seems to be working fine, my icons show up, and there are no more errors.  So unless you are customizing and using LESS files, you probably won't come across this exact issue that I had, but if you are, those "hard-coded" paths are the issue.

**Comment by cwilli34** [comment]
So since we don't use gulp for the semantic-ui-ember library, is there a way during ember installation to have those URL's in the default/global/site.variables from `../../themes/....etc.` to point to the correct path's?

**Comment by mintymac** [comment]
Any word on this?   Thanks to everyone that commented.

**Comment by aaronbhansen** [comment]
Going to release beta 2 today. After that, all paths should be customizable. See the documentation commit https://github.com/Semantic-Org/Semantic-UI-Ember/commit/c7aa66fd84f2922f7566ac022552f776d8560ff3 and the actual change for more information https://github.com/Semantic-Org/Semantic-UI-Ember/commit/9cc8eed70ba224916c4dd85907a5d4b958ceb811.

You should be able to configure each of the settings as needed for your local repos.
