### ISSUE TITLE
dropdown example in README throws an error 

### ISSUE THREAD

**Issue by jgamedev** [Semantic-Org/Semantic-UI-Ember#106]
When copying and pasting the example usage for the dropdown component I'm getting the following error on Ember 2.5

> Uncaught Error: Assertion Failed: You specified a quoteless path to the {{action}} helper which did not resolve to an action name (a string). Perhaps you meant to use a quoted actionName? (e.g. {{action 'save'}}).

Changing the variable name to anything other than 'action' fixes it for me.

**Comment by aaronbhansen** [comment]
Could you provide the whole template example?

**Comment by jgamedev** [comment]
I think it was a complete copy and paste of what is there, nothing else.

**Comment by aaronbhansen** [comment]
Thanks, I updated the dropdown example.
