### ISSUE TITLE
TypeError: renderNode is undefined

### ISSUE THREAD

**Issue by TSchnaars** [Semantic-Org/Semantic-UI-Ember#107]
I am receiving this error when I open a modal or use the tabs and I wanted to see if you all had any insight on how to fix it.  IDK if it is definitely your lib that is causing it, but I thought this might be a good place to ask.  Thanks for all your help and for doing an awesome job with this.

**Comment by aaronbhansen** [comment]
Could you provide a little more info on how you're opening the modal?

**Comment by TSchnaars** [comment]
Hi @aaronbhansen. It seems as if I was calling the modal from a parent component that housed the child component.  I put the modal call in the action in the child component and it seems to have fixed everything.  Thanks!

**Comment by aaronbhansen** [comment]
Glad to hear you found a solution.
