### ISSUE TITLE
Popup with pre-existing HTML?

### ISSUE THREAD

**Issue by denchen** [Semantic-Org/Semantic-UI-Ember#109]
Can I use `{{#ui-popup}}` with preexisting HTML rather than using the `content` field? If so, how?

**Comment by aaronbhansen** [comment]
Yes, just pass html to the popup and it will bind correctly. You might need to create a computed property and mark it as a Safe String so Ember doesn't try to escape the html.

```{{#ui-popup html="<div>Something</div>"}}```

**Comment by denchen** [comment]
My popup is rather complicated. I have several `{{#if}}` statements, an `{{#each}}` loop, a button with a bound `{{action}}`, as well as several bound values. Can I actually use handlebar notation within the `html` attribute? And actually, it seems rather ugly to stick a huge chunk of html into an attribute like that. Is there another way, like putting my HTML in block invocation form?

**Comment by jlukic** [comment]
I'm not sure about ember integrations, but in vanilla SUI you can include a `popup` as the preceding `dom` element from the activating element, and it will automatically bind correctly. This will prevent you from having to use metadata attributes.

**Comment by aaronbhansen** [comment]
@denchen did you get anywhere else on this or can we close this?

**Comment by denchen** [comment]
What I ended up doing was creating my entire HTML popup markup in the template, and then in the component, instantiate the popup. In other words

Template:

    <div class="ui popup bottom right transition hidden">
      <div class="ui card">
        ...
      </div>
    </div>

Component:

    didRender() {
      let popup = this.$('#popup-link');
      popup.popup({
        delay: {
          show: 100,
          hide: 800
        },
        inline: true,
        on: 'click',
        offset: '0',
        position: 'bottom right',
        transition: 'slide down',
        variation: 'basic'
      });
    }

Probably not the best way or even the correct way of doing things, but it works.

**Comment by aaronbhansen** [comment]
Glad to hear you found a solution. I think in 95% of the situations, Semantic-UI-Ember works, but there are a few outliners that are easier to do outside of the components.
