### ISSUE TITLE
Closing modal on approve

### ISSUE THREAD

**Issue by seifsallam** [Semantic-Org/Semantic-UI-Ember#11]
By default after approval, modal view doesn't get dismissed. But calling `this.send('closeModal');` doesn't respect transition settings from the view. Also returns this error `Uncaught TypeError: Cannot read property 'height' of undefined`

**Comment by aaronbhansen** [comment]
This has been updated to no longer use closeModal. We can't call the appropriate callbacks for semantic if we are disposing of the outlet code directly.
