### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined for dropdown example

### ISSUE THREAD

**Issue by alsravya** [Semantic-Org/Semantic-UI-Ember#110]
Just copy pasted the code from dropdown 
Code is building but getting an error : Uncaught TypeError: Cannot read property 'call' of undefined

**Comment by aaronbhansen** [comment]
There was an issue on the read me. I've updated it. Let me know if that fixes it for you.

**Comment by alsravya** [comment]
I will check that. I have a question related to it. 
Can we use 2 frameworks eg: both bootstrap and semantic UI for developing same web page/ web application

**Comment by aaronbhansen** [comment]
If you can provide an example online we can look at it further, but we also release the 2.0 beta. Please try it on the latest and reopen if its still an issue with how to reproduce.
