### ISSUE TITLE
Ember build -prod --> Error: Broken @import declaration of "theme.css"

### ISSUE THREAD

**Issue by joseperales** [Semantic-Org/Semantic-UI-Ember#114]
When made a build in ember-cli 2.6.1 

On OS X El Capitan and Windows 10 I try to build Ember build -prod and produce Error: Broken @import declaration of "theme.css"

![screen shot 2016-06-12 at 7 37 54 a m](https://cloud.githubusercontent.com/assets/236926/15990938/afd0411a-3070-11e6-94f2-d04c30b907b8.png)

**Comment by aaronbhansen** [comment]
Are you compiling the css from the semantic less?

**Comment by joseperales** [comment]
No semantic less, it could be closed, was related to ember-cli broccoli, now updated and working great

**Comment by aaronbhansen** [comment]
Great thanks
