### ISSUE TITLE
Modal name seems not to matter

### ISSUE THREAD

**Issue by cwilli34** [Semantic-Org/Semantic-UI-Ember#115]
The name parameter doesn't seem to matter.  If I have multiple modals in one template they all open anyways unless I give them different classes and call those in my function.  So in my component template I have:

`<button class="ui green button" {{action 'openModal' 'create-project'}}>Open Modal</button>`

In my component.js file:
```
actions: {
        openModal: function(name) {
            console.log(name);
            $('.ui.modal.create.project').modal('setting', 'closable', false).modal('show');
        },
```

The first tag of my modal:
`{{#ui-modal name="create-project" class="create project"}}`

I have also tried `$('.ui.modal.create.project').modal('setting', 'closable', false).modal('show', name);`.  If I remove the .create.project class names, then the function opens all my other modals.  Is there something I am missing?

**Comment by aaronbhansen** [comment]
Based on your selector this should work, its hard to tell without looking at all the code. Did you find any solutions? Can we close this ticket?

**Comment by cwilli34** [comment]
@aaronbhansen Sorry for the late response.  

The only thing that seemed to work was adding a defining class to the modal, such as `{{#ui-modal name="response-message" class="response message"}}`, and then calling it like `$('.ui.modal.response.message').modal().modal('show'); `

So this shouldn't be closed.  This is still an issue.  What other code do you need to see?
