### ISSUE TITLE
NameError when I try to change @themesFolder in theme.config

### ISSUE THREAD

**Issue by cwilli34** [Semantic-Org/Semantic-UI-Ember#120]
In my theme.config I have the following values:

```
/*******************************
            Folders
*******************************/

/* Path to theme packages */
@themesFolder : 'src/themes';

/* Path to site override folder */
@siteFolder  : 'app/styles/site';

/*******************************
         Import Theme
*******************************/

@import "app/styles/theme";

/* End Config */
```

I have a themes folder in my ember app: `app/styles/themes`

However I get the following error: 

```
NameError: variable @positiveTextShadow is undefined in bower_components/semantic-ui/src/definitions/elements/button.less on line 3212, column 16:
3211   color: @positiveTextColor;
3212   text-shadow: @positiveTextShadow;
3213   background-image: @coloredBackgroundImage;

File: bower_components/semantic-ui/src/definitions/elements/button.less (3212)
The Broccoli Plugin: [LessCompiler] failed with:
undefined
```

In my ember-cli-build.js file I have the lessOptions as:

```
lessOptions: {
            paths: [
                'bower_components/semantic-ui'
            ]
        },
        outputPaths: {
            app: {
                css: {
                    app: "assets/css/dashboard.css"
                },
                js: "assets/js/dashboard.js"
            },
            vendor: {
                css: "assets/css/vendor.css",
                js: "assets/js/vendor.js"
            }
        },
        SemanticUI: {
            css: false,
            javascript: true,
            fonts: true,
```

So why am I getting this NameError and why can't I change the themesFolder variable to use my own custom directory for themes?  The themes directory right now is just a copy from the src directory.  It should work.  If I change the path to `src/themes`, everything works as expected.

**Comment by aaronbhansen** [comment]
Are you trying to compile your own less css in the project? Sounds more like a build pipeline error.

**Comment by cwilli34** [comment]
Just the app.less file under the styles directory in my Ember.js project.  And what would be causing a build pipeline error?

**Comment by aaronbhansen** [comment]
I haven't personally tried to compile the semantic less into css in a project yet. I don't really know where to go to help you with it. The error seems more related to ember-cli and the build process than semantic-ui-ember. Maybe try the less addon for help.
