### ISSUE TITLE
Enumerable#contains deprecation warnings

### ISSUE THREAD

**Issue by Panman8201** [Semantic-Org/Semantic-UI-Ember#122]
As of ember 2.8.0-beta.1, `Enumerable.contains()` has been depreciated in favor of `Enumerable.includes()`. Semantic-UI-Ember uses the depreciated function several times in the `base.js` Mixin.

http://emberjs.com/deprecations/v2.x/#toc_enumerable-contains

**Comment by aaronbhansen** [comment]
Thanks for the issue. I saw your pull request. If you want to re-open we could do something like

```
_containsOrIncludes(array, value) {
  if (typeof array.includes) {
    return array.includes(value);
  }
  return array.contains(value);
}
```

Seems like the easiest way to have a private method to wrap and check until 3.0. Thoughts?

**Comment by Panman8201** [comment]
That's actually a pretty good idea, I'll work on another PR soon.
