### ISSUE TITLE
Popup crashes when class is altered

### ISSUE THREAD

**Issue by jfarlow** [Semantic-Org/Semantic-UI-Ember#125]
I have a popup which has it's class affected during user interaction.

```
{{ui-popup class=selectedClass}} 
   <i class="icon></i>
{{/ui-popup}}
```

if selectedClass changes during user interactions, the popup object crashes:

```
set: {
          position: function(position, calculations) {

            // exit conditions
            if($target.length === 0 || $popup.length === 0) {   <--{cannot read length of nil}
              module.error(error.notFound);
              return;
            }
```

I suspect there should be an existence check on $target & $popup in addition to a length check for the position function.

Is the existence of these objects found by means of tracing their entire class path?  If so, is there a better way to do this?

**Comment by aaronbhansen** [comment]
Thanks for reporting that, I'll get a test created. I suspect its related to the render cycle and I need to add a isDestroying check. If not it might be a semantic-popup bug

**Comment by jfarlow** [comment]
Relatedly, but maybe not, is there a mechanism to hook 'onClick' to an ember action from within a popup?

The ultimate goal was to try to create a popup object which could behave like any other semantic-ui object.  The two abilities I was looking for (and had an old subclassed object to help with), were 1) class changes, and 2) action assignments.


In general, working with a popup breaks parts of semantic-ui's behavior because it inserts an ember div object where there otherwise wouldn't have been one: 

```
<div class="ui buttons>
   {{#ui-popup content="hi"}}
       <button class="blue button" {{action 'buttonPress'}}>
              hello
        </button>
   {{/ui-popup}}
</div>
```

yields:
```
<div class="ui buttons">
  <div class="ember>
     <button class="blue button">
     </button>
   </div>
</div
```


To address this, I had created a subclass of the old ui-popup to assign a tag and class to the popup itself.  This now works for free in 2.0 - great!

```
<div class="ui buttons>
   {{#ui-popup content="hi" tag="button" class="blue}}
              hello
   {{/ui-popup}}
</div>
```

BUT, there is no way for me to assign the action to this button.  I'd like to have something like:
```
<div class="ui buttons>
   {{#ui-popup content="hi" tag="button" class="blue **onClick=('action' 'buttonPress')**}}
              hello
   {{/ui-popup}}
</div>
```

But this (and a number of other things I've tried don't seem to work and I can't figure out how I might get access to the onClick of the button.

**Comment by aaronbhansen** [comment]
As far as I know the Ember component class doesn't expose any onClick actions. There is a click method that gets called, but you would need to extend the ui-popup and plug into that event directly. http://emberjs.com/api/classes/Ember.View.html#toc_method-implementation

With that said, I did add a new extension in 2.0 to change the scope of what element is selected. Normally the method that is called is the element itself, but there is a property you can pass in that will allow you to specify the element you want the selector to be one. In your example you could do something like

```
{{#ui-popup class="ui buttons" onElement="button.button" content="hi"}}
  <button class="button" {{action "something"}}>Click Me</button>
{{/ui-popup}}
```

That functionality isn't really documented yet as I wanted to test and explore it more, but you could try it out. The problem with ember is we always need to have a scope and a component in which the to instantiate semantics modules with. This option would let you move the component up and specify the scope underneath the current component.

**Comment by aaronbhansen** [comment]
I'm trying to replicate the class change error in a test, but not having much luck. Maybe you can layout how to replicate the error. Meaning the class name is ... then its open, then ...

**Comment by jfarlow** [comment]
```
<div class="ui buttons">
{{#ui-popup content="Browse" tagName="button" class=browseButtonClass}}
 				 <i class="find icon"></i>
{{/ui-popup}}
{{#ui-popup content="Search" tagName="button" class=searchButtonClass}}
 				 <i class="search icon"></i>
{{/ui-popup}}
</div>
```

where:
```
searchButtonClass: function(){
    if( isSearching){
        return 'ui blue button';
     }else{ 
        return 'ui grey button';
     }
}.property('isSearching'),
```

On first load, everything works great, popovers do as they should, buttons look (are classed) correct.

However, when something (button press) changes the isSearching boolean, which triggers a change of class, then I get the error:

"semantic.js:10762 Uncaught TypeError: Cannot read property 'length' of undefined"
centered on line:


```
set: {
          position: function(position, calculations) {
            // exit conditions
            if($target.length === 0 || $popup.length === 0) {   <---------- HERE
              module.error(error.notFound);
              return;
            }
```

**Comment by aaronbhansen** [comment]
I tried to replicate this in tests and locally, I can't get it to error. Going to close this issue unless you can replicate it in a test

**Comment by aaronbhansen** [comment]
Added and pushed a test for it. Can't replicate locally
