### ISSUE TITLE
Clicking on top left <a> tag gives a 404.

### ISSUE THREAD

**Issue by jscottchapman** [Semantic-Org/Semantic-UI-Ember#126]
<img width="193" alt="screen shot 2016-07-28 at 8 52 03 am" src="https://cloud.githubusercontent.com/assets/10002902/17217154/961e3534-54a0-11e6-8ab3-847fcf7376e1.png">
Clicking on the "UI Docs" <a> tag takes you to "http://semantic-org.github.io/" and shows a 404.  
<img width="970" alt="screen shot 2016-07-28 at 8 54 08 am" src="https://cloud.githubusercontent.com/assets/10002902/17217239/e020b18e-54a0-11e6-926b-af3e696e5c96.png">

**Comment by aaronbhansen** [comment]
Thanks for catching that. I updated it in code and it will fixed on the next docs release
