### ISSUE TITLE
Docs home page link

### ISSUE THREAD

**Issue by khornberg** [Semantic-Org/Semantic-UI-Ember#127]
![image](https://cloud.githubusercontent.com/assets/3442051/17248039/39a8057e-555d-11e6-90ae-340cc2f29df3.png)

When clicking `UI Ember Docs` I was expecting to go to http://semantic-org.github.io/Semantic-UI-Ember/#/modules instead I ended up at http://semantic-org.github.io/ which is a 404 page.

**Comment by aaronbhansen** [comment]
Thanks for reporting. I've fixed the docs.
