### ISSUE TITLE
Popup: `html` support SafeStrings

### ISSUE THREAD

**Issue by Panman8201** [Semantic-Org/Semantic-UI-Ember#130]
Since Ember SafeStings are technically objects which are converted to strings via `.toString()`, the popup `html` attribute (and likely others) don't like SafeStrings. I've made a helper to call `.toString()` before being passed in but it'd be nice if the components would handle that themselves.

And to add to this discussion, `Ember.String.isHtmlSafe()` was [added in ember 2.8](http://emberjs.com/blog/2016/07/25/ember-2-7-and-2-8-beta-released.html#toc_code-ember-string-ishtmlsafe-code), but there is a [polyfill](https://www.npmjs.com/package/ember-string-ishtmlsafe-polyfill). However, the "old" way of doing this is to [check the `instanceof`](https://github.com/froala/ember-froala-editor/blob/v2.3.4/addon/components/froala-editor.js#L57).

**Comment by aaronbhansen** [comment]
Could you provide an example so we can make a test?

**Comment by Panman8201** [comment]
I can't get a ember twiddle to work, but basically something like;

```js
// app/controllers/foo.js
import Ember from 'ember';
export default Ember.Controller.extend({
  someHtml: Ember.computed({
    get() {
      return Ember.String.htmlSafe('<strong>foobar</strong>');
    }
  })
});
```

```hbs
{{!-- app/templates/foo.hbs --}}
{{ui-popup tagName="i" class="help circle icon" html=someHtml}}
```

**Comment by aaronbhansen** [comment]
Good news, I found a good way unwrap all values passed in. See this commit for for more information https://github.com/Semantic-Org/Semantic-UI-Ember/commit/2391acaa5718851607c74b6828d4c4a38a8dfe8b.

It does everything but execute. Since all the internal execute methods already are unwrapped, I figured its best to leave it up to individuals calling it in their repo to handle any specific execute code.

**Comment by seawatts** [comment]
@aaronbhansen I'm using this on ember 2.10 and it no longer works.

**Comment by aaronbhansen** [comment]
Here is my updated helper
```
import Ember from 'ember';

export function popupHtml(params, hash) {
  let obj = Ember.merge({}, hash); // the hash is a readonly EmptyObject. You must clone it to edit it
  return window.$.fn.popup.settings.templates.popup(obj);
}

export default Ember.Helper.helper(popupHtml);
```

**Comment by seawatts** [comment]
Yeah I'm using latest
