### ISSUE TITLE
No updates for 2.2.3?

### ISSUE THREAD

**Issue by v3ss0n** [Semantic-Org/Semantic-UI-Ember#132]
Semantic-ui is 2.2.3 now but ember version needing some love. Everyone busy?

**Comment by Panman8201** [comment]
I've been using the `2.0.0-beta.0` release of this addon with SUI `2.2.2` without issue. All you need to do is update your `bower.json` dep: `bower install semantic-ui --save`

**Comment by v3ss0n** [comment]
ok thinks , i will try

**Comment by aaronbhansen** [comment]
Feel free to put in a pull request if you see a change and would like to have it updated.

**Comment by v3ss0n** [comment]
tested with 2.2.4 so far. it is working fine.

**Comment by mylanconnolly** [comment]
Just wanted to add my $0.02; it appears that 2.2.4 is working well for me, also. I'll work on a MR over the next couple days as I get some free time if no one else does it between now and then.

**Comment by aaronbhansen** [comment]
This will be updated on the release today
