### ISSUE TITLE
Any roadmap for 2.0 release?

### ISSUE THREAD

**Issue by v3ss0n** [Semantic-Org/Semantic-UI-Ember#133]

**Comment by aaronbhansen** [comment]
There are a few bugs that need tests added, and mostly waiting for enough people to test it to ensure nothing was missed in the upgrade process. We have been using it in production fine for a month, and haven't had any issues. The bugs reported haven't effected us, I think they are mostly outliners. It comes down to getting time to finish off remaining items, if you want to help out let me know and I can come up with a list of items to complete.

**Comment by v3ss0n** [comment]
i will help , i am started using semantic-ui for ember. Still comparing Semantic vs BS4 for mobile hybrid dev.

**Comment by aaronbhansen** [comment]
Great, if you want to do a small pull request, we need to update Semantic ui to 2.2.3 like you mentioned in your other ticket and add an ember try for 2.2.2. There is already an ember try for semantic latest, so we just need the last version added. Once thats in I can get some send some more tickets over

**Comment by aaronbhansen** [comment]
Releasing beta 2 today, if no more issues come up in a week, I will be releasing 2.0
