### ISSUE TITLE
Update Dropdown?

### ISSUE THREAD

**Issue by nojacko** [Semantic-Org/Semantic-UI-Ember#135]
I've been using the dropdown menu with dynamic content, i.e. the items in the dropdown can change.

The list options correctly update with the Ember models. However, the text for the currently selected option doesn't update. Picture will explain this better:

![screen shot 2016-08-22 at 19 33 54](https://cloud.githubusercontent.com/assets/1667141/17866846/ff84ca70-689f-11e6-820b-5df2a4950d35.png)

What I did: 
* Changed selected "One"
* Renamed "One" to "One (edited)"

The list updated, but not currently selected text.

I've tried calling `this.$().modal('refresh')` but that removes the dropdown completely. 😕 

How can I force the dropdown to update?

**Comment by aaronbhansen** [comment]
I'll probably need some code examples as the actual dropdown items are all controlled inside your code. It should just render what you have there in the template. 

We have a specific situation where we created a custom dropdown and on selection change the selected text to something else, but thats working outside of ember and we call some of the dropdown methods directly.

**Comment by nojacko** [comment]
I'll provide an example when I've got a moment. Is there a standard JSBin for Semantic-UI-Ember I could use?

**Comment by aaronbhansen** [comment]
Anymore on this or should I close the issue?

**Comment by tabeth** [comment]
Ditto on the comment @aaronbhansen made. As a potential fix, you could consider using an observer on your dropdown elements to manually change the text. Depending on your situation, this might not be necessary, though.
