### ISSUE TITLE
Lonely else in index.js

### ISSUE THREAD

**Issue by khornberg** [Semantic-Org/Semantic-UI-Ember#138]
If I set the option to not use the semantic ui javascript files provided, I get a build error.

Removing the else at https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/index.js#L37 fixes the problem.

**Comment by aaronbhansen** [comment]
Thanks, I just removed it. If you want to pull down the latest commit and test it.

**Comment by khornberg** [comment]
Yep that works
