### ISSUE TITLE
[ui-checkbox] checked property

### ISSUE THREAD

**Issue by lnaravindan** [Semantic-Org/Semantic-UI-Ember#140]
When we toggle the 'checked' property bound to the ui-checkbox, the associated actions like 'onChecked', 'onUnchecked' are not firing. 

Example.

{{#ui-checkbox checked=checkStatus onChecked=(action 'onChecked') }}

When the checkbox is unchecked, if I do

this.set('checkStatus', true); 

I expect that the onChecked and other callbacks to fire, but it didn't.

**Comment by aaronbhansen** [comment]
That was on purpose for performance reasons and to avoid infinite loops.

If you think about the ember lifecycle, if we called the actions each time the property was set, we would create loops

init life cycle

1. initialize component
2. send onChecked method
3. didUpdateAttrs
4. repeat #2 

There is code to stop that from happing within Semantic-UI-Ember, but its also creates extra work that has to be done. If you take that same lifecycle for updating attrs, its the same process if we called the callback each time

1. didUpdateAttrs
2. send OnChecked
3. repeat #1 

The idea with DDAU rewrite is an action has to take place to fire that action up. Setting data isn't an action, its just the Data Down part of that process. If you know you are going to be setting the data and want to do related actions, I would recommend something like ember-composable-helpers, then you could do pipe commands to fire off multiple actions.

```
<div class="ui button" (pipe-action (action "doClick") (action "setChecked") (action "onChecked")) >
```

**Comment by lnaravindan** [comment]
@aaronbhansen  Thanks for the reply.  Following is my use case. 

I have a checkbox to which I have binded a value.
{{ui-checkbox checked=checkStatus onChecked=(action 'onChecked') }}
{{#if flag}}

{{/if}}

In the onChecked action, I will be doing few stuff and computing whether or not to set the 'flag'.
I am maintaining the checkbox state and when the user reloads the page again, I will be setting/unsetting the checkbox based on the last save state. For this I want the "onChecked" event to fire because the logic for setting the flag is in the "onChecked" action handler. In this case, I can't have a user interaction but then I want an action to be fired during the initial render.

Please let me know your comments on this.
