### ISSUE TITLE
Hide sidebar when a link item onclick 

### ISSUE THREAD

**Issue by gponsu** [Semantic-Org/Semantic-UI-Ember#142]
When in the sidebar component, I click on a menu item, it send me to the page, but the sidebar is left open.

If it is a normal link, it is easy to close the sidebar:

```hbs
{{#ui-sidebar as |execute|}}
    <a class="item" {{ action execute 'hide' }}>
      Works!
    </a>
{{/ui-sidebar}}
```

But if there is a link with the helper `#link-to`, how I can do?

```hbs
{{#ui-sidebar as |execute|}}
    <div class="item">
      {{#link-to "login"}}
        Sign In
      {{/link-to}}
    </div>
{{/ui-sidebar}}
```

I have tried in many ways, but none works for me.

Thank you very much!

**Comment by aaronbhansen** [comment]
Unfortunately the link-to helper doesn't have any actions at the moment to hook into. The easiest solution would be to use something like dockyards composable helpers. 

```
{{#ui-sidebar as |execute|}}
    <a class="item" {{pipe-action (action execute 'hide') (action (invoke "transitionToRoute "login" this))}}>
      Works!
    </a>
{{/ui-sidebar}}
```

Or instead of the invoke helper, call a custom action and call transitionToRoute in your controller

**Comment by gponsu** [comment]
Thank you very much aaronbhansen, it has worked for me :blush:

**Comment by Panman8201** [comment]
FYI, while I think a combination of a "regular" `<a>` tag in combination with the [`ember-href-to` addon](https://github.com/intercom/ember-href-to) is the better option, there is also the [`ember-link-action` addon](https://www.emberobserver.com/addons/ember-link-action).

**Comment by gponsu** [comment]
Thank you very much Panman8201, I did'nt know these addons, I'm going to try! :)
