### ISSUE TITLE
Remove the deprecation for Enumerable#contains

### ISSUE THREAD

**Issue by bartocc** [Semantic-Org/Semantic-UI-Ember#144]
Ember 2.8 introduced a deprecation when using Enumerable#contains.

It should be replaced with Enumerable#includes. See http://emberjs.com/deprecations/v2.x/#toc_enumerable-contains

**Comment by utilityboy** [comment]
@bartocc this has already been addressed in #143

**Comment by bartocc** [comment]
thx @utilityboy. @aaronbhansen told me the same in my PR #145
