### ISSUE TITLE
searchFields for ui-search does not accept arrays.

### ISSUE THREAD

**Issue by tabeth** [Semantic-Org/Semantic-UI-Ember#146]
Following the convention set in [the official docs](http://semantic-ui.com/modules/search.html#/settings) results in unpredictable behavior. 
```
{{#ui-search
  searchFields=['item']
}}
...
{{/ui-search}}

```

The fix is just to not use brackets:
```
{{#ui-search
  searchFields='item'
}}
...
{{/ui-search}}
```

I haven't looked into whether or not this is a limitation of Handlebars and/or Ember or a bug in Semantic-UI-Ember. Regardless, I think this information should be known to the public, just in case anyone encounters a similar issue.

**Comment by Panman8201** [comment]
That's a Handlebars limitation. You'll have to define the array on your controller/component and pass the property. Or, if you're using the [ember-composable-helpers addon](https://github.com/DockYard/ember-composable-helpers#array), 
`{{#ui-search searchFields=(array 'item')}}`

**Comment by tabeth** [comment]
Ah, that's what I suspected; I ended up just defining the array in the controller/component as you mentioned. At the very least, hopefully the existence of this conversation will help someone out there.

**Comment by allthesignals** [comment]
I tried to use an array (with `source` instead of `searchFields`) and semantic threw errors about API missing a url. I wonder if anyone experiences this?
