### ISSUE TITLE
Changing Multiple Dropdown item seperator.

### ISSUE THREAD

**Issue by ozanorhan** [Semantic-Org/Semantic-UI-Ember#149]
Right now it uses ',' while passing the elements. I've checked documentation and couldn't find any way to change delimiter. How can i achieve this?

**Comment by Panman8201** [comment]
Not sure I follow. I'm using the `onChange()` action and get an array as the first argument (of selected items). Or when passing into `selected`, I pass an array.

**Comment by aaronbhansen** [comment]
Internally Semantic returns an array of values that we handle and return on the onChange event. For ember you should be passing in an array and receiving one back. If you have text that has commas in it, then you can change the [delimiter](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L3527). Just pass it in as a parameter. 
```
{{ui-dropdown delimiter="|"}}
```
