### ISSUE TITLE
jQuery 3 and Semantic UI Rating

### ISSUE THREAD

**Issue by khornberg** [Semantic-Org/Semantic-UI-Ember#150]
jQuery 3 seems to break Semantic UI rating
https://github.com/Semantic-Org/Semantic-UI/issues/4561

We are seeing this on CI builds under the `ember-release` scenario because `Ember 2.8` allows jQuery [`<4`](https://github.com/emberjs/ember.js/blob/v2.8.1/bower.json#L8]). It currently pulls in `3.1.1`.

In Ember 2.7 and below it is [`<3`](https://github.com/emberjs/ember.js/blob/v2.7.3/bower.json#L8).

**Comment by khornberg** [comment]
I'm not sure if this is the best way to go about fixing this issue, but [specifying jQuery <3 in the ember try scenario makes the build pass](https://github.com/Semantic-Org/Semantic-UI-Ember/pull/141/commits/5e775f827dbff00a8106ebe7a40159ecb626409d).

Perhaps a note saying that rating only works with `jQuery <3` for the time being will allow things to progress.

**Comment by aaronbhansen** [comment]
Yeah that works, I'm fine specifying jquery < 3 for older ember builds. If you want to put a pull request out we can get it merged in. Thanks!
