### ISSUE TITLE
tabindex not getting passed to ui-dropdown component

### ISSUE THREAD

**Issue by James1x0** [Semantic-Org/Semantic-UI-Ember#152]
The default input created for tab selection is automatically created with a `tabindex` of `0`. Passing a tabindex to the ui-dropdown component doesn't change that, and it seems like it's impossible to work around.

/cc @jscottchapman

**Comment by Panman8201** [comment]
One workaround is to extend the component and define `tabindex` as a bound attribute. Ex:

```js
// app/components/ui-dropdown.js
import UiDropdown from 'semantic-ui-ember/components/ui-dropdown';

export default UiDropdown.extend({
  attributeBindings: ['tabindex']
})
```

**Comment by James1x0** [comment]
@Panman8201 I should have added "work around w/o extending your own component", but thank you, that will definitely work.

It feels as though this should be a default attribute binding in any case, mainly because tabindex is a frequently used attribute in forms.

**Comment by aaronbhansen** [comment]
@James1x0 if you want to create a pull request with attribute bindings on the base mixin with these three attributes and create a test, I'll merge it in

```
autofocus
tabindex
title
```

Those three feel like they are the only ones that directly relate to the semantic components from the ember [text support](https://github.com/emberjs/ember.js/blob/v2.7.0/packages/ember-views/lib/mixins/text_support.js#L117) component.  Disabled and readonly are handled on the specific components.

**Comment by James1x0** [comment]
@aaronbhansen Doesn't seem to solve the issue with search selection, though.

**Comment by aaronbhansen** [comment]
If you add tab index to non ember semantic dropdown does it behave the same way? If so that change would need to go to the other repo.

**Comment by James1x0** [comment]
@aaronbhansen Indeed... Semantic-Org/Semantic-UI#4490

**Comment by aaronbhansen** [comment]
Okay, looks like its a bug on the actual module and not related to Ember. If you still want to add the attribute bindings in a pull request I can get that merged in

**Comment by aaronbhansen** [comment]
This has been added on this commit https://github.com/Semantic-Org/Semantic-UI-Ember/commit/7ffd5a4502f264d3a0cae99ad8b4522f07208b3e and will be released shortly.
