### ISSUE TITLE
`this.attrs.hasOwnProperty()` not available in ember 2.9.0-beta's

### ISSUE THREAD

**Issue by Panman8201** [Semantic-Org/Semantic-UI-Ember#156]
It appears in the latest ember 2.9 beta, the `attrs` are technically an `EmptyObject` instance, which doesn't have the `hasOwnProperty()` method. I've run into Errors from both `ui-popup` component and `ui-checkbox` mixin.

https://github.com/Semantic-Org/Semantic-UI-Ember/blob/2.0.0-beta.2/addon/components/ui-popup.js#L12

https://github.com/Semantic-Org/Semantic-UI-Ember/blob/2.0.0-beta.2/addon/mixins/checkbox.js#L17

**Comment by aaronbhansen** [comment]
@Panman8201 you can try this commit and see if it fixes it for you https://github.com/Semantic-Org/Semantic-UI-Ember/commit/82951e60fe0917b1f2be3e69b53cdb1eb409e884

**Comment by aaronbhansen** [comment]
Any feedback @Panman8201

**Comment by Panman8201** [comment]
Sorry, busy on other things ATM. Haven't had time to lock in that commit but will try to later today.

**Comment by aaronbhansen** [comment]
beta 3 was released and fixes this

**Comment by Panman8201** [comment]
Just updated to beta 3, seems to be good now. Thanks
