### ISSUE TITLE
Popup content gets set to title in production only

### ISSUE THREAD

**Issue by ScottShannon** [Semantic-Org/Semantic-UI-Ember#157]
When using the ui-popup component locally on my machine, the title and content correctly display.  However, I send everything into production, the content and title text are the value of the title parameter.  I have also observed this behavior on your documentation example.  Screenshot below.
Currently use Ember 2.7.0 and the documentation site I see is on 2.8.1.  Let me know if any further details are required.
`{{#ui-popup content="description" title="header"}}
    <i class="fa fa-check-circle"></i>
{{/ui-popup}}`
![image](https://cloud.githubusercontent.com/assets/13679970/19132225/98dde8d0-8b20-11e6-8be9-28b47ee9f62e.png)

**Comment by aaronbhansen** [comment]
I found this too. This is actually a Semantic bug I open up a pull request for https://github.com/Semantic-Org/Semantic-UI/pull/4614.

The solution at the moment is too pass in the full html.

**Comment by ScottShannon** [comment]
Thank you for that information.  In the meantime I have made a helper to accept the title and content and return them as html that can be passed to the popup html property.  I had to do this to pass in my dynamic content.  Posting here to save a few minutes for whoever runs into this.

**helper** (Change the double quote to backticks, had to switch it to format this)
`
export default Ember.Helper.extend({
	compute(params, hash) {
		let title = Ember.Handlebars.Utils.escapeExpression(hash.title);
		let content = Ember.Handlebars.Utils.escapeExpression(hash.content);
		return "<div class="header">${title}</div><div class="content">${content}</div>";
	}
});
`

**Template usage**
`
{{#ui-popup html=(popup-html content=controllerProperty title="Put title here")}}
<i class="fa fa-check-circle"></i>
{{/ui-popup}}`
