### ISSUE TITLE
Asset path for themes with less

### ISSUE THREAD

**Issue by edeis53** [Semantic-Org/Semantic-UI-Ember#162]
How to properly resolve theme assets using ember-cli-less?

Build file specifies: 
 `fonts: 'assets/themes/default/assets/fonts'` and writes them there accordingly. 

However, Semantic is looking the the wrong path, outside of assets folder, and 404s for fonts, et.c
`/themes/default/assets/fonts/icons.ttf`

```
SemanticUI: {
  // These flags allow you do turn on or off auto imports for Semantic UI
  import: {
        css: false,
        javascript: true,
        image: true,
        fonts: true
  },
  // These settings allow you to specify the source of the Semantic files
  source: {
    css: 'bower_components/semantic-ui/dist',
    javascript: 'bower_components/semantic-ui/dist',
    images: 'bower_components/semantic-ui/dist/themes/default/assets/images',
    fonts: 'bower_components/semantic-ui/dist/themes/default/assets/fonts'
  },
  // These settings allow you to specify the destination of the Semantic files
  // This only applies to images and fonts, since those are assets
  destination: {
    images: 'assets/themes/default/assets/images',
    fonts: 'assets/themes/default/assets/fonts'
  }
}
```

If I change theme.config to use material theme for everything:

Semantic is looking not only outside of assets, but also for the material subfolder: `/themes/material/assets/fonts/icons.woff`

and fonts are written into default theme instead of material folder: `assets/themes/default/assets/fonts`

WORK AROUND: for default theme: (build file)

```
      destination: {
        images: 'themes/default/assets/images', 
        fonts: 'themes/default/assets/fonts'
      }
```

However, same work around doesn't work if using material theme for all settings in themes.config.
eg. 

```
      destination: {
        images: 'themes/material/assets/images', //defaults to: 'assets/themes/default/assets/images', but semantic isn't looking there.
        fonts: 'themes/material/assets/fonts'
      }
```

The font files are loaded, eg. `/themes/material/assets/fonts/icons.woff2`, however they aren't display, just a square icon shows up instead. 

The CSS compiled seems to match however.

```
@font-face {
  font-family: 'Icons';
  src: url("../../themes/material/assets/fonts/icons.eot");
  src: url("../../themes/material/assets/fonts/icons.eot?#iefix") format('embedded-opentype'), url("../../themes/material/assets/fonts/icons.woff2") format('woff2'), url("../../themes/material/assets/fonts/icons.woff") format('woff'), url("../../themes/material/assets/fonts/icons.ttf") format('truetype'), url("../../themes/material/assets/fonts/icons.svg#icons") format('svg');
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-decoration: inherit;
  text-transform: none;
}
```

IDEALLY, shouldn't the CSS always get compiled to match the :destination: in the build-config, or perhaps have the :destination: generated based on the current theme?

Setup references:
https://github.com/nathanpalmer/example-semantic-ui-ember-cli
http://semantic-org.github.io/Semantic-UI-Ember/#/modules/usage

**Comment by edeis53** [comment]
Best workaround so far:

Leave icon and image set to use default theme in theme.config, but change all the others to material.
```
/* Elements */
@button     : 'material';
@container  : 'material';
@divider    : 'material';
@flag       : 'material';
@header     : 'material';
@icon       : 'default';
@image      : 'default';
```

Then in ember-cli-build.js, specify default theme, outside of ember assets folder.
```
      destination: {
        images: 'themes/default/assets/images',
        fonts: 'themes/default/assets/fonts'
      }
```

-Shouldn't semantic be able to be correct to look for in the `/assets/themes...` folder if specified as such?

**Comment by aaronbhansen** [comment]
It sounds like you have some kind of configuration issue possibly with ember-cli-less or your project. If you look at the [semantic css](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css#L7176), assets/themes isn't specified, just ./themes.

All css and files should go under /assets in the dist folder according to [ember cli](https://ember-cli.com/user-guide/#css).

**Comment by edeis53** [comment]
Interesting. I see the correct path in that CSS file.

In the .less I see `'../../themes/default/assets/fonts'` with a note about "Modified in gulp for dist"
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/globals/site.variables#L354

What options need to be set for less to have it compile correctly?
```
    lessOptions: {
      paths: [
        'bower_components/semantic-ui'
      ]
    },
```

In the CSS for my app, the less is being compiled as follows:
```
@font-face {
  font-family: 'Icons';
  src: url("../../themes/default/assets/fonts/icons.eot");
  src: url("../../themes/default/assets/fonts/icons.eot?#iefix") format('embedded-opentype'), url("../../themes/default/assets/fonts/icons.woff2") format('woff2'), url("../../themes/default/assets/fonts/icons.woff") format('woff'), url("../../themes/default/assets/fonts/icons.ttf") format('truetype'), url("../../themes/default/assets/fonts/icons.svg#icons") format('svg');
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-decoration: inherit;
  text-transform: none;
}
```

**Comment by edeis53** [comment]
Alright, now we are getting closer. 

Looks like the source path correction to relative path is performed in grunt here:
https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/config/project/config.js#L90

However, with semantic-ember we are using ember-cli-less and not grunt. How to correct?

**Comment by khornberg** [comment]
@edeis53 I am using `ember-cli-less` along with Semantic UI material theme for icons.

My config looks like this:
```
'import': {
    'images': false,
  },
  'source': {
    'css': 'bower_components/semantic/dist',
    'javascript': 'bower_components/semantic/dist',
    'fonts': 'bower_components/semantic/dist/themes/material/assets/fonts',
  },
  'destination': {
    'fonts': 'assets/themes/material/assets/fonts/',
  }
```

Note that this uses a custom build of Semantic UI built before the inclusion into the ember app, that is separately so that `ember-cli-less` is not building Semantic UI. Semantic UI is installed via bower into `semantic` not `semantic-ui`.

**Comment by aaronbhansen** [comment]
Once a good path is figured out, if either of you want to create documentation we can have a guide for others in the future.

**Comment by lypborges** [comment]
Hi, any update or docs on how to setup theme with semantic-UI-ember?

**Comment by khornberg** [comment]
@lypborges This issue and https://github.com/Semantic-Org/Semantic-UI-Ember/issues/7 have working examples / ideas in them. 

You have two basic options:
1) Customize and build SUI *outside* the ember build process
2) Customize and build SUI *within* the ember build process

I'm partial to option 1 but understand the desire for option 2

**Comment by aaronbhansen** [comment]
Anyone want to take a stab at adding PR to extend the docs for this?

**Comment by khornberg** [comment]
Depends on the direction which we want to recommend.

I'm currently working on building SUI outside of the ember build process again. I could contribute what I find that works.

As for building SUI within the ember build process, that posses more challenges.

**Comment by aaronbhansen** [comment]
@khornberg I feel like the best direction is to have documentation for building it outside of this addon, but that could be documentation for building it totally outside of ember or in your own ember  cli build process. 

I think either way of building it (outside of your ember project or in), gets you the same results. A while back we tried to build it in Ember, but were getting a lot of conflicts between trying to run less and sass at the same time. We haven't gone back to explore after that. 

Lets start with the easiest path, which is creating documentation outside ember and if someone in the future wants to tackle it, they can document how to add it to your Ember build pipeline.

**Comment by Panman8201** [comment]
This should be achievable simply by having this addon installed and the `ember-cli-less` addon. Then `SemanticUI.import.css = false` in the environment config and add the bower paths to the `ember-cli-less` options. No? Something similar to what's [documented on the `ember-cli-bootswatch` addon](https://github.com/Panman8201/ember-cli-bootswatch#usage-with-ember-cli-less). 

(I haven't dealt with custom SUI builds yet, so I could certainly be wrong. But if it's just CSS changes you're going for, I would think this would suffice.)

**Comment by khornberg** [comment]
@edeis53 With regards to the original question

> How to properly resolve theme assets using ember-cli-less?

That requires either modifying the ember-cli build to output files to match what `semantic ui` is expecting or to modify `semantic ui` itself to look in a different location.

To modify semantic ui is more involved. `Semantic-UI-Ember` can be set up to build the CSS of semantic ui by importing the LESS file from Semantic UI. The problem becomes where does one get the source files from and how are one persist the changes. 

One can bower install semantic ui; however, unless you check in your `bower_components` and modify the source files there, those changes will not persist. 

So one is left to either decide to build semantic ui outside of your ember project and include the built files in the ember build process (like `semantic-ui-ember` does). Or add the custom semantic ui to the source files and use ember-cli to build semantic ui from the inlined semantic ui.

With regards to whether or not `Semantic-UI-Ember` should support or document building semantic-ui via ember-cli, that is a different question and should be moved to a different issue. I think the responses on this issue answer the original question

**Comment by Panman8201** [comment]
@khornberg I don't think that's the intention of how to handle Less changes, you shouldn't be changing source files. Instead, import the source files and change any [variables provided](http://semantic-ui.com/usage/theming.html).

**Comment by khornberg** [comment]
@Panman8201 I think we discussing good things but they should be moved off this issue.
