### ISSUE TITLE
Addon usage: Cannot read property 'SemanticUI' of undefined

### ISSUE THREAD

**Issue by ScottShannon** [Semantic-Org/Semantic-UI-Ember#165]
Semantic-UI-Ember version: 2.0.0-beta.2
My addon index.js include
```javascript
included: function(addon) {
    this._super.included.apply(this, addon);
}
```
This produces an error on build: Cannot read property 'SemanticUI' of undefined
Which is referring to this line in Semantic-UI-Ember/index.js
```javascript
included: function (app) {
    var options = (app && app.options['SemanticUI']) || {}; // DOES NOT WORK IN ADDONS
}
```

Is there any way to use this addon as a nested addon?

**Comment by ScottShannon** [comment]
After looking at how a few other addons work as nested addons, I have a fix that makes it possible for this addon to nested.
`var options = (app && app.project.config(app.env)['SemanticUI']) || {}; // FIX: THIS WORKS`
This should also work in a top level project, but that part should be tested still.  Would you be open to accepting a PR for this?

**Comment by aaronbhansen** [comment]
A fix would be great. If can reference a few of the projects you found, so I can view them quickly that would help. Thanks!

**Comment by ScottShannon** [comment]
I have one on hand (chaotic tabbing habits, I close them right away but still have 20 open).
https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/index.js#L172

**Comment by khornberg** [comment]
I've run into this as well but never looked for the fix. Thanks @ScottShannon

**Comment by aaronbhansen** [comment]
The fix was merged in. Thanks @ScottShannon
