### ISSUE TITLE
Closure actions in component blocks

### ISSUE THREAD

**Issue by gponsu** [Semantic-Org/Semantic-UI-Ember#167]
I am trying to use closure actions and it gives me this error:

> ember.debug.js:11651 Uncaught Error: An action could not be made for `onApprove` in <webapp@controller:register::ember618>. Please confirm that you are using either a quoted action name (i.e. `(action 'onApprove')`) or a function available in <webapp@controller:register::ember618>

This is my code, what am I doing wrong?

```hbs
{{#ui-modal class="tiny" context=".component.context"
  onApprove=(action 'registerCompleted') onHidden=(action 'denyModal') as |modal|}}
  <i class="close icon"></i>
  <div class="register-form content">
    {{registration-form user=model onRegister=(action onApprove target=modal)}}
  </div>
{{/ui-modal}}
```

Thank you very much!

**Comment by aaronbhansen** [comment]
Sounds like the action might not exist on your controller or component? I don't know what it would be other than that
