### ISSUE TITLE
Error with "action execute" calls on modules.

### ISSUE THREAD

**Issue by Vrakfall** [Semantic-Org/Semantic-UI-Ember#169]
Hello,

I'm trying to make a sample project out of the doc and can't get it working properly with all the docs I went through. I might be missing something really important. I'm actually able to get Semantic modules generated by ember but I get stuck when I try to interact with them and use actions on them.

I tried many different things but the closer I got was by following [this guide](http://semantic-org.github.io/Semantic-UI-Ember/#/modules/usage).

## Details on what I did. To see the actual error, please go to the end of my explanation.

1.  I first installed ember: `npm install -g ember-cli`.
2.  Then I created a new test project: `ember new testEmberSemantic`
3.  Created the basic templates and a component for my future accordion test:

```bash
ember generate template application
ember generate template index
ember generate component accordion-test
```

4.  Then I install `Semantic-UI-Ember` and generate it:

```bash
ember install semantic-ui-ember
ember generate semantic-ui-ember
```

5.  I then put the following in `templates/components/accordion-test.hbs`:

```handlebars
{{yield}}

{{#ui-accordion as |execute|}}
  <div class="title">
    Semantic UI
  </div>
  <div class="content">
    Be sure to check out <div class="ui button" onclick="{{action (execute 'open' 1)}}">the example</div>
  </div>
  <div class="title">
    Example
  </div>
  <div class="content">
    This is a great example!
  </div>
{{/ui-accordion}}
```

6.  I added a simple `{{accordion-test}}` in `templates/index.hbs` and `{{outlet}}` in `templates/application.hbs`.

## The error encountered.

7.  Then, if I try to run `ember server` and load the webpage at `localhost:4200`, I have the following error in the console with nothing rendered on it.

```
Assertion Failed: A helper named "execute" could not be found
```

If I try the same without the `execute` and `action` parts in `templates/components/accordion-test`, I get a normal page but, of course, without event handler on the button.

I kinda guessed, from what I read from the docs than it implicitly calls a method on the ui-accordion component in the base mixin that is supposed to call the method on the semantic component but it's not clearly said.

I even tried to add the following in `components/accordion-test`, just to make sure I wasn't required to create the "helper" myself.

```javascript
import Ember from 'ember';

export default Ember.Component.extend( {
  actions: {
    execute( command, argumentOne ) {
      $( '.ui.accordion' ).accordion( command, argumentOne );
    }
  }
} );
```

But that didn't help.
I think the main problem probably comes from my usage of `Semantic-UI-Ember` but this is the closest I can get to something working based on what I can find in the docs. Maybe that needs to be updated, to make sure a newcomer can get to a working example easily.

~~Also, I did all of this using `node v7.1.0` and did not think it could be coming from it. However, I should try soon if it works with `node 6.9.1`. I wasn't able to, yet.~~

**Edit:** I tried this with node `6.9.1` aswell and had no better results, so it doesn't seem to be linked with the node version, here.

Thank you for your patience while reading this. :)

**Comment by Rev3rse** [comment]
Same error here.

**Comment by Vrakfall** [comment]
I've got the same issue whether I nest it or not. What else did you do to get that result, @Rev3rse , please?

**Comment by Panman8201** [comment]
@Vrakfall try this instead; `<a class="ui button" {{action (action (execute "open" 1))}}>the example</a>`

**Comment by Vrakfall** [comment]
@Panman8201 I still get the same error:

```
Assertion Failed: A helper named "execute" could not be found
```

**Comment by fortm** [comment]
@Vrakfall  I am getting same error, did you find how to make this work ?

**Comment by Panman8201** [comment]
Humm... `execute` is [technically already a closure action](https://github.com/Semantic-Org/Semantic-UI-Ember/blob/2.0.0/app/templates/components/ui-accordion.hbs#L1), so I wonder if it should be called like this instead: `{{action execute "open" 1}}` or `{{action (action execute "open" 1)}}`

**Comment by fortm** [comment]
@Panman8201 , thanks `{{action (action execute "open" 1)}}` works

**Comment by aaronbhansen** [comment]
Thanks for the help @Panman8201

**Comment by bockscar** [comment]
Installed Ember/Semantic-UI-Ember and was running through examples per initial post above for this issue. Got same errors as original post. Not sure if fixes above (which work) reflect new guidance for use of Semantic-UI-Ember overall? Or if the docs are out of date and remain erroneous?

**Comment by aaronbhansen** [comment]
For anyone looking at this, the documentation always recommends you use 
`onclick={{action (execute 'open' 1)}}` to properly use the execute as a closure action. If you don't use it with onclick, then you have to use the work arounds listed here.
