### ISSUE TITLE
Handle closing modal

### ISSUE THREAD

**Issue by seifsallam** [Semantic-Org/Semantic-UI-Ember#17]
In the latest semantic ui update, `closeModal` is deprecated. Checking the code, i found this

```
// if controller handles approves, they must manually call view.execute('hide')
```

How do i access view from controller, and run `execute` on it. AFAIK, ember only works in one direction. You can only bubble upward, but you can't call view nor send it events. Is there something I'm missing here?

**Comment by aaronbhansen** [comment]
If you need to override a method for the modals standard approve or deny, you can create an action to represent that. 
```
actions: 
   approve: (view) ->
       # execute your code
       # when finished
       view.execute('hide')
```

**Comment by seifsallam** [comment]
That makes sense, but what about actions outside `approve` and `cancel` scope? In my case I have an extra button that should delete an object, then close modal. Is there any way to handle such thing?

**Comment by aaronbhansen** [comment]
If you look at the code for cancel on the semantic model, once it starts closing you can't stop it like you can with approve and deny. We do fire a hide action you can plug into to do some clean up, but you can't stop the action it's self. 

To manually close outside of approve and deny just pass the view in from the template.
```
<div class="ui button" {{action "close" view}}>Nevermind</div>
```
then you still have access to the view, which has the semantic modal mixin and the execute function.

**Comment by aaronbhansen** [comment]
One more comment. The modal is unique compared to other semantic modules. Usually we can just dispose of the html and not worry about it, but with modal we have ensure we go through semantic first and then through ember so semantic properly executes its code and visually looks correct. The only way to do that is by first executing the events on semantic and then once it's callbacks are finished, then dispose of the outlet. It's a little awkward in the traditional ember workflow, but it was the only way we could find to probably execute.

**Comment by seifsallam** [comment]
Awesome. It worked! Thanks a lot :)
