### ISSUE TITLE
How to use Sidebar?

### ISSUE THREAD

**Issue by allthesignals** [Semantic-Org/Semantic-UI-Ember#170]
Hello,

Thanks for your work on this project.

How do I use the sidebar component? The documentation gives an example, but I'm not sure how to use this API to toggle the sidebar. [Here](http://semantic-ui.com/modules/sidebar.html#/definition) it says I should make a controller action, but I'm not sure what context is passed to that action and what methods to call on it. Are there any examples for how to use this? I couldn't find anything in the tests.

Thanks!

**Comment by khornberg** [comment]
The docs are generated from `tests/dummy/app`, so you can use those as a reference as you tried to do.

The particular implementation of the sidebar action is defined in https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/tests/dummy/app/controllers/modules/sidebar.js

From the [documentation](http://semantic-org.github.io/Semantic-UI-Ember/#/modules/sidebar), the above controller and action are what the action refers to in
`<div class="ui button" onclick="{{action 'toggle' 'sub-sidebar'}}">`

**Comment by finferflu** [comment]
I have the following in my `application.hbs`:

```handlebars
<div class="ui button" onclick="{{action 'toggle' 'sub-sidebar'}}">
  Toggle
</div>

<div class='ui bottom attached pushable component context'>
  {{#ui-sidebar class='vertical menu' context=".component.context" id="sub-sidebar"}}
    <a class='item'>One</a>
    <a class='item'>Two</a>
    <a class='item'>Three</a>
  {{/ui-sidebar}}

  <div class='pusher'>
    <h1 class='ui header'>Title</h1>
    {{outlet}}
  </div>
</div>
```

And this is in my `application.js` controller:

```javascript
import Ember from 'ember'

export default Ember.Controller.extend({
  actions: {
    toggle: function (id) {
      Ember.$(`#${id}`).sidebar('toggle')
    }
  }
})
```

However, when I click on my toggle button, nothing happens. Am I missing anything? 

Thanks!
