### ISSUE TITLE
Could i use this addon offline?

### ISSUE THREAD

**Issue by hugoruscitti** [Semantic-Org/Semantic-UI-Ember#173]
Hi!, i noticed that semantic-ui uses online fonts from google-fonts. But i need to use offline without access to google-fonts. It's possible to use this addon offline?

I see a related issue, but i don't understand how to combine with this addon:

https://github.com/Semantic-Org/Semantic-UI/issues/1521

Thanks!

**Comment by khornberg** [comment]
Yes it is possible to use this addon offline.
This addon makes it simpler to use Semantic UI in Ember. If your ember application can work offline, so will this.

As for the fonts you have two options:
1. Let the network request the font and fail. SUI will revert back to a system font.
2. Make a custom build of SUI to use with this addon. In the issue you referenced, Jack mentioned how to change SUI to not include the online fonts.

**Comment by aaronbhansen** [comment]
Thanks for the response @khornberg
