### ISSUE TITLE
Variations in popup

### ISSUE THREAD

**Issue by fhals** [Semantic-Org/Semantic-UI-Ember#174]
Is there any way to using variations in [popup](http://semantic-ui.com/modules/popup.html) such as flowing and fluid?

**Comment by Panman8201** [comment]
Apply the class name when using component: `{{#ui-popup class="fluid" content="foobar"}}`

**Comment by aaronbhansen** [comment]
You should be able to pass any value to the component as if it was the actual Semantic Module. Please read more on the [documentation](http://semantic-org.github.io/Semantic-UI-Ember/#/modules/usage)
