### ISSUE TITLE
Dropdown onLabelCreate function throws error

### ISSUE THREAD

**Issue by seawatts** [Semantic-Org/Semantic-UI-Ember#178]
When overriding the `onLabelCreate` callback on the `ui-dropdown` it throws an error
![image](https://cloud.githubusercontent.com/assets/2148546/21786914/3fedf570-d67b-11e6-8b8c-76347c49eec8.png)

**Comment by aaronbhansen** [comment]
The trace looks like its coming from semantic-ui. My guess is you're not returning the right parameters. If you want to create a test pr and a fix we can merge it in
