### ISSUE TITLE
Dynamic popup example broken

### ISSUE THREAD

**Issue by James1x0** [Semantic-Org/Semantic-UI-Ember#179]
The dynamic popup example doesn't work for me.
http://semantic-org.github.io/Semantic-UI-Ember/#/modules/popup

**Comment by Panman8201** [comment]
More specifically, the popup content does not update when the parent property/value changes. I've tried to `$E.set('content','foobar');` directly on the component instance and that doesn't even update the popup. It's like the new value does not make it to the SUI module...

**Comment by James1x0** [comment]
Yes, this is actually biting us where we have computed content/html properties for popups. It seems like the initial value is getting set as the computed property getter, not the result of the computed property. So as it stands, cps are not working with pop-ups. Boo!

**Comment by aaronbhansen** [comment]
There is a known semantic issue where if you set [title and content it doesn't get updated](https://github.com/Semantic-Org/Semantic-UI-Ember/issues/157). Please create a test and a pr replicating your issue.

**Comment by James1x0** [comment]
@aaronbhansen Tried to make a test and it worked. So I did some digging and I was behind on my release at 2.0.0-beta.3, updated to 2.0.1 and it works properly.

The issue still exists on the demo site, so I'm going to swap the title again.

**Comment by aaronbhansen** [comment]
Good to hear. The demo site has the title bug mentioned before, just waiting for my pull request to get it fixed on the main semantic repo.

**Comment by allthesignals** [comment]
Hmm, I updated as well, but I'm still seeing the issue. 
bower:
    "semantic-ui": "^2.2.10",
    "semantic-ui-popup": "^2.2.6"

package.json:
   "semantic-ui-ember": "2.0.1"

**Comment by ngouy** [comment]
Why this is closed, 

It's still an ongoing issue

**Comment by ngouy** [comment]
ok
https://github.com/Semantic-Org/Semantic-UI/commit/8f38205254f0e3ac5517a4de44ef922e1ac33342#diff-49e1ad4a7d18de50c8f075f246cd1036

will be resolved with sementic-ui 2.3 (current : 2.2.14)

Is there a reason for ember-sementic-ui to be stucked in 2.2.14 ?

**Comment by ngouy** [comment]
👍 
np was just asking

**Comment by ngouy** [comment]
Is there a way to have more description on what is missing to see if we can help ? Tickets with 3.2 labels are very succincts :/
