### ISSUE TITLE
Semantic UI Ember ui-search not updating when source attr is computed

### ISSUE THREAD

**Issue by allthesignals** [Semantic-Org/Semantic-UI-Ember#181]
Suppose this is the controller and template:
```
  // controller
  searchables: Ember.computed('model', function() {
    // return array of objects [{title: value, title: value}];
  })

  // template
  {{#ui-search  source=searchables
                onSearchQuery=(action (mut query)) 
                onSelect=(action 'transitionTo')
                class='item'}}
    <input class="prompt" type="text" placeholder="Search Features/Investments">
    <div class="results"></div>
  {{/ui-search}}
```

`searchables` is a computed property and should update semantic-ui with new searchable values, but this doesn't not seem to be happening - it's always retaining the old values even when `searchables` is recomputed. When I use `{{log searchables}}` in the template, I'm noticing the computed property is updating there correctly. 

I'm happy to write a failing test, but I want to make sure I'm not missing something obvious.

Thank you!

**Comment by khornberg** [comment]
I may be off base. I am curious if the same behavior is exhibited if computed property is part of a component. I've often (though I'm not exactly sure why) problems with my templates not updating when CPs change when the CP is part of a controller. My problems and this problem may be entirely unrelated. Just my first thought as I read this.

**Comment by moranje** [comment]
Nope, I have used it in a component. I use a direct call to semantic to have it consume the local object when it is available.

**Comment by aaronbhansen** [comment]
@allthesignals if you can write a test we can look at fixing it. Thanks

**Comment by aureliosaraiva** [comment]
@allthesignals  I found the bug and I'm working in a solve.

Do you solve this problem?

**Comment by aureliosaraiva** [comment]
@allthesignals Yes, I'm testing the solution.

**Comment by aureliosaraiva** [comment]
Problem simulation: https://ember-twiddle.com/56f28ca7aecd9e6fc17b824a900596e3
