### ISSUE TITLE
Sidebars - how to implement in Ember > 2.7

### ISSUE THREAD

**Issue by edeis53** [Semantic-Org/Semantic-UI-Ember#182]
How to avoid the following errors and properly implement the sidebar?
```
Sidebar: Had to add pusher element. For optimal performance make sure body content is inside a pusher element

Sidebar: Had to move sidebar. For optimal performance make sure sidebar and pusher are direct children of your body tag
```
Old technique was a hack for the application view file. Which is now deprecated > 2.7
```
export default Ember.Component.extend({
  classNames: [ 'pusher' ],
  tagName: ''
});
```
See: https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/tests/dummy/app/views/application.js

Deprecated:
```In 2.6.0, you could put a component at app/views/application.js but that will not work in Ember 2.7 (and its horrible) so it isn't very useful...```
https://github.com/emberjs/ember.js/issues/13690

**Comment by renefs87** [comment]
I confirm this is not working neither on Ember 2.12

**Comment by utilityboy** [comment]
I've moved to using ember-elsewhere with Semantic's sidebar styling and it works quite well if that helps anybody.

**Comment by renefs87** [comment]
@utilityboy can you please provide an example? I am trying to do it but the sidebar is still being displayed within ember divs... I guess I'm doing something wrong...

**Comment by utilityboy** [comment]
@renefs87 sure:

In `application.hbs`:

```
  {{#from-elsewhere name="right-sidebar" as |sidebar|}}
    <div class="ui {{if sidebar "visible"}} overlay right sidebar vertical menu">
      {{component sidebar}} {{!-- I have a little component that I render for all sidebars --}}
    </div>
  {{/from-elsewhere}}
```

`sidebar.hbs`

```
<div class="sidebar-wrapper">
  <h3 class="sidebar-header ui dividing header">
    <div style="float: right;">
      <i class="small close link icon" onclick={{onCancel}}></i>
    </div>
    <div class="content">
      {{title}}
    </div>
  </h3>
  <div class="sidebar-content">
    {{yield}}
  </div>
</div>
```

Styles:
```
.ui.right.sidebar.vertical.menu {
  // we need to override some of semantic-ui's default styles
  // this is because we are using semantic styling with ember-elsewhere
  visibility: visible;
  opacity: 0;
  background: #f9fafb;
  transition: 0.2s;
  width: 400px;

  &.visible {
    opacity: 1;
  }

  .sidebar-wrapper {
    background: #fff;
  }

  .sidebar-header {
    padding: 1em;
    margin-bottom: 0;

    i {
      padding: 0;
      margin: 3px 0 0;
      float: right;
    }
  }

  .sidebar-content {
    background: #fff;
    padding: 1em;
    margin-top: 0;
  }

  .actions {
    margin: 1em -1em -1em;
  }
}
```

**Comment by khornberg** [comment]
I am using the sidebar in Ember 2.8 without issue. I had to restructure my code a bit but it made it simpler.

```
//main content component with tagName  = ''
<div class="pushable">
  {{ui-sidebar}}...{{/ui-sidebar}}
</div>
<div class="pusher">
...{{yield}}
</div>
```

I include that component on in the application.hbs and all works.
The communication between the button to show/hide the sidebar is done via Ember's eventbus.

**Comment by edeis53** [comment]
@khornberg this issue is implementing sidebar in any route other than application route.

**Comment by khornberg** [comment]
Ok, 
I think that if you have `div.pushable` and the children of `div.ui.sidebar` and `div.pusher` as siblings, it should work without complaint.

I think, this shows that it is possible:
http://semantic-org.github.io/Semantic-UI-Ember/#/modules/sidebar
https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/tests/dummy/app/templates/modules/sidebar.hbs

**Comment by edeis53** [comment]
Thanks @khornberg 

Declaring div.pushable and the context class worked.

```<div class="ui pushable segment component context">
  {{#ui-sidebar class="inverted menu left inline vertical" context=".component.context" id="sub-sidebar"}}
    <a class="item">Item 1</a>
    <a class="item">Item 2</a>
    <a class="item">Item 3</a>
  {{/ui-sidebar}}
  <div class="pusher">
    <div class="ui basic segment" style="min-height: 300px;">
      Sub Content Here
    </div>
  </div>
</div>
```
