### ISSUE TITLE
Ember-engines support

### ISSUE THREAD

**Issue by nickschot** [Semantic-Org/Semantic-UI-Ember#189]
Currently when trying to use semantic-ui in an in-repo-engine it fails because it will try to do setup again (e.g. copy non-existent fonts, images) which causes a broccoli error. Situation is likely identical when using in a normal in-repo addon.

Ember-paper had a similar issue which was solved here: https://github.com/miguelcobain/ember-paper/pull/594 and some relevant talk in: https://github.com/ember-engines/ember-engines/issues/315#issuecomment-273573144

I can later provide an example application if needed.

**Comment by aaronbhansen** [comment]
I haven't used it as an in-repo addon. I haven't had any need, this is the first request for it also. Feel free to fix it and submit a PR and demo project if you need this functionality.

**Comment by nickschot** [comment]
Thanks for the swift reply, I'm new to engines but I'll surely give it a go!

**Comment by aaronbhansen** [comment]
You'll have to explain a little more why it needs to move to npm. From my understanding bower should be used for front end resources. Everything in semantic ui is a front end resource thats never referenced directly in an ember app. You would never use an `import something from 'semantic-ui'` statement in your ember app as its not referenced.

**Comment by nickschot** [comment]
Ember is moving away from bower entirely, don't have full time to explain right now. Is also related to fastboot.

**Comment by aaronbhansen** [comment]
Right, I know they are moving bower for app dependencies, but from what I heard they still would have bower for front end dependencies. Things like lightbox and semantic ui. It makes sense to have npm import shim module for something like moment js you need to reference in your app, but for items that are layered on top I haven't seen a good explanation to move them over to npm yet.

**Comment by nickschot** [comment]
Roughly my current idea: I think at least ember-engines and normal in-repo-addon's don't have support for bower so either there need's to be a way to stop the includes hook from firing in the engine. This just results in a less clean solution if it's only the engine needing the dependency as it'll have to be in the parent's bower.json. 

I'll probably come across it if it's a necessity! I'll dig into it and let you know.
