### ISSUE TITLE
Getting rejected by sanitizer error

### ISSUE THREAD

**Issue by krzkrzkrz** [Semantic-Org/Semantic-UI-Ember#19]
On Ember CLI 0.2.3. I get this in Ember Inspector, console tab:

    downloadable font: rejected by sanitizer (font-family: "Icons" style:normal weight:normal stretch:normal src index:1) source: http://localhost:4099/assets/themes/default/assets/fonts/icons.woff2

I am also using Firefox. Any ideas?

**Comment by aaronbhansen** [comment]
I'm guessing possibly your contentSecurityPolicy is rejecting this. Ensure font-src is *
```
 contentSecurityPolicy: {
     ... (other CSP settings)
      'font-src': "*"
    },
```

**Comment by aaronbhansen** [comment]
Didn't see any further response, closing.
