### ISSUE TITLE
Using search with ui-dropdown causes action to be fired twice 

### ISSUE THREAD

**Issue by kevintraver** [Semantic-Org/Semantic-UI-Ember#193]
```{{#ui-dropdown class="ui fluid search selection" selected=selected_type onChange=(action 'myEvent') as |execute mapper|}}```

`myEvent` gets fired twice

This can be repeated with the example app

**Comment by pijus-vaskevicius-ht** [comment]
using `selected` together with `onChange` causes this, not search class, at least in my case.

**Comment by ngouy** [comment]
Tested and not the case in example app.

This can be closed
