### ISSUE TITLE
Two outdated dependensies

### ISSUE THREAD

**Issue by w96k** [Semantic-Org/Semantic-UI-Ember#195]
See: https://david-dm.org/Semantic-Org/Semantic-UI-Ember
```ember-cli-babel
^5.1.7	6.4.1	7.0.0-alpha.2```
```ember-runtime-enumerable-includes-polyfill
^1.0.1	2.0.0	2.0.0
```

**Comment by w96k** [comment]
And 10 dev-dependencies. Seems like this project has no maintainer or has lots of problems :)

**Comment by Panman8201** [comment]
I know the current maintainers are looking for more help. Once I get back on to ember projects I'd like to help here but that won't be until this winter.

At the same time, I'm surprised that it seems like Semantic-UI itself seems to be maintained by one person (or very few anyway).

**Comment by aaronbhansen** [comment]
Correct, I'm not actively maintaining it. I've reached out on ember slack, but haven't had any interest. 
I've actually re-written most the modules to be Ember only with no Semantic UI javascript, and I am testing those out locally as in-repo add-ons. In the future I plan to release those once I finish the last two modules.  
Everything works fine for this add-on, and we still use Semantic-UI-Ember, I just don't plan on putting anymore time into this project at the moment.

**Comment by khornberg** [comment]
@aaronbhansen Once you release those rewritten modules what is the point of this repo or will this become those rewritten modules?

**Comment by aaronbhansen** [comment]
Internally we plan to stop using semantic and create a minified version of the framework thats mobile first and much smaller size wise. Since its a smaller size, I don't plan to support all the current modules or CSS. If you want all the features, you should stay with this code base. If you only end up using half or less (like we do), then the alternative is a better solution.

**Comment by Panman8201** [comment]
I think I can make this addon only import the proper semantic-ui modules (via configuration) to help with that. Just wish I had more time to help out here now.

@aaronbhansen If you want to add me to the repo, I could try to at least update ember-cli & deps. Or I guess I could submit PR's if you'd rather go that route.

**Comment by w96k** [comment]
I would like to help, but I'm very new to ember and not that good with js either. Glad, that you had answered.

**Comment by aaronbhansen** [comment]
No problem, the library works and should continue to work. The ember code is dynamic and just a wrapper over Semantic-UI's javascript. For the most part there isn't anything custom, just a wrapper connecting the two. The dependencies for ember just need to be updated.

**Comment by wuarmin** [comment]
It would be great if somebody could keep the deps updated. We started using semantic ui with ember and use this addon and I think lots of other people use it in prod. :-)

**Comment by aureliosaraiva** [comment]
@aaronbhansen Do you can close this issue in favor https://github.com/Semantic-Org/Semantic-UI-Ember/pull/199

**Comment by khornberg** [comment]
With the [desire for jQuery to be removed from ember](https://github.com/emberjs/ember.js/issues/16058) itself @aaronbhansen any chance those modules that you have worked on could be released?

**Comment by aaronbhansen** [comment]
I'm no longer maintaining this repository as we've converted all our of internal code off of Semantic-UI-Ember to in-repo-addon replacements. We are still looking for anyone that wants to maintain this repository.

I've made all of our in-repo-addons public. If someone wants to do the actual work of converting these to addons and maintaining it, we can talk more.  If you're interested in looking at what I've done you can view the repositories here.

https://github.com/crowdox/simple-semantic-ui-modal
https://github.com/crowdox/simple-semantic-ui-transition-mixin
https://github.com/crowdox/simple-semantic-ui-dimmer
https://github.com/crowdox/simple-semantic-ui-accordion
https://github.com/crowdox/simple-semantic-ui-progress
https://github.com/crowdox/simple-semantic-ui-radio
https://github.com/crowdox/simple-semantic-ui-checkbox

For the dropdown, I decided to user power select as it was more maintained and did more already. The pieces I used to make it work are in this gist.
https://gist.github.com/aaronbhansen/3153855ed2be887fb2f677a74d058dfa

There is a very minor amount of jQuery in the in-repo-addons as we still use it. But in one or two changes it could be pulled out I believe. I tried to make them almost purely using Embers built in library. 

Feel free to look at the code and if someone wants to take the next step of converting them to addons I'm okay with that, we just dont' have time at the moment to maintain them other than for what we use them for. We've been using them in production for 6+ months now with no issues.

**Comment by khornberg** [comment]
Thank you @aaronbhansen 

I'd like to see semantic-ui-ember v3 be jQuery-less by implementing the modules within the Ember framework.

All of that though in light of https://github.com/Semantic-Org/Semantic-UI/issues/6109

@championswimmer

**Comment by championswimmer** [comment]
@khornberg 
Yes my next plan of action is to see how to reduce jQuery wherever possible. I am currently working on that

For now waiting on @aaronbhansen to provide me npm access so I can make releases of 

 - `2.0.2` Last version to support ember 1.13.x versions (adds fastboot compat) 
 - `2.1.0` first version to drop bower, works with ember 2.x versions but not 3.x
 - `3.0.0-beta1` first release with ember 3.0 support

All 3 are tagged and ready to be released

**Comment by championswimmer** [comment]
For the time being, you can use 

`ember install Semantic-Org/Semantic-UI-Ember#3.0.0-beta1`

**Comment by championswimmer** [comment]
@khornberg @w96k 
I have made new releases into NPM 

Outdated dependencies are mostly gone. Rest will go away soon.
Currently I am maintaining v3, which has focus on Ember LTS 2.12, 2.16 2.18 and Ember latest 3.0  (it does support Ember 3.1 beta too)
