### ISSUE TITLE
Icons font with ember-cli

### ISSUE THREAD

**Issue by alanbhamilton** [Semantic-Org/Semantic-UI-Ember#2]
The font-awesome `icons.*` font files are 404-ing on page load with ember-cli. In `semantic.css` the src property is `src: url("themes/default/assets/fonts/icons.eot");` but the font assets are not making it to the *dist* folder so they can be served by ember-cli.

**Comment by aaronbhansen** [comment]
Thanks, we'll test out the pull request and get it merged in soon.
