### ISSUE TITLE
Grids don't seem to be working in an Ember CLI app

### ISSUE THREAD

**Issue by krzkrzkrz** [Semantic-Org/Semantic-UI-Ember#20]
On an Ember CLI app 0.2.3. The grid displays funny. As in, instead of the grid taking up 1440px, it takes up 1444px, which forces the horizontal scroll bar to show.

I have `app/pods/application/template.hbs`

```
    <div class="ui grid">
      <div class="row">
        <div class="four wide column green">4</div>
        <div class="four wide column blue">4</div>
        <div class="four wide column yellow">4</div>
        <div class="four wide column red">4</div>
      </div>
    </div>
```

It looks like:

![screen shot 2015-04-07 at 10 09 01 pm](https://cloud.githubusercontent.com/assets/390072/7025008/372b6bbe-dd73-11e4-94cf-0a9a697fc445.png)

Any ideas?

**Comment by aaronbhansen** [comment]
I don't know what would cause this, considering there is no css in the semantic ember project. It's only a passthrough of the original semantic project. Have you tried recreating the grid outside of ember cli? My guess is semantic-ui isn't working as expected (which would be a semantic-ui bug), ember cli is adding styles that are messing with the semantic-ui, or your project is styling something that is causing it to break. We haven't seen any issues on our projects with this, granted we are on ember cli 0.2.1 on our projects, but I'm not sure what a newer ember cli project would do to cause this to work improperly.

**Comment by jlukic** [comment]
Use a `padded grid` or `horizontally padded grid` if you're using a full page top level grid. Grids use negative margins which will cause horizontal scroll unless you set `overflow-x: hidden` on `html`.

**Comment by krzkrzkrz** [comment]
@jlukic thanks. That works!
