### ISSUE TITLE
ui-accordion: settable properties not pulling correct keys

### ISSUE THREAD

**Issue by ScottShannon** [Semantic-Org/Semantic-UI-Ember#203]
semantic-ui-ember version 2.0.1
semantic-ui version: 2.2.10

This component does not seem to be pulling settable property keys correctly.  In the screenshot below, I added console logs to see what settings were available, and also shows the setting I was attempting to pass in.

![image](https://user-images.githubusercontent.com/13679970/28944255-df932afa-786f-11e7-8ea2-98eaf56b8c8e.png)

**Comment by championswimmer** [comment]
reopen if unresolved
