### ISSUE TITLE
`ember generate semantic-ui-ember` seems like a redundant installation step for ember-cli:2.14.1

### ISSUE THREAD

**Issue by jithinbp** [Semantic-Org/Semantic-UI-Ember#205]
The second step as per the [README.md](https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/README.md) pulls in bower dependencies, but that has already been done by the `ember install` step, and feels like a redundant effort. 

ember-cli:2.14.1 , node: 6.3.1 , os: linux-x64

```bash
myprompt/frontend $ ember install semantic-ui-ember

WARNING: Ember CLI is using the global NPM, but your NPM version has not yet been verified to work with the current Ember CLI release.
NPM: Installed semantic-ui-ember
installing semantic-ui-ember
  install bower package semantic-ui
NPM: Installed bower
  not-cached https://github.com/Semantic-Org/Semantic-UI.git#*
  resolved https://github.com/Semantic-Org/Semantic-UI.git#2.2.13
Bower: Installed semantic-ui=semantic-ui
Installed addon package.

myprompt/frontend $ ember generate semantic-ui-ember

installing semantic-ui-ember
  install bower package semantic-ui
  cached https://github.com/Semantic-Org/Semantic-UI.git#2.2.13
Bower: Installed semantic-ui=semantic-ui
myprompt/frontend $ 
```

A possibly relevant comment from a [thread on this subject](https://discuss.emberjs.com/t/what-does-ember-install-do/9405/4)

```
ember install <addon-name>

is an exact replacement for

    npm install <addon-name> --save-dev
    ember generate <addon-name>
```

P.S : I am not a packaging expert, and am merely providing user feedback. Please close without comment if the second step does more than what is output in the prompt.

**Comment by championswimmer** [comment]
This is true, it isn't required for ember-cli >= 2.14 
Documentation states that now
