### ISSUE TITLE
Ui-radio with object not `checked`

### ISSUE THREAD

**Issue by esbanarango** [Semantic-Org/Semantic-UI-Ember#21]
Hello and thank you for this project.

I'm trying to use the `ui-radio`and setting the __value__ and __current__ to objects, it does the binding well, but it doesn't check the one that is already pre-selected.

````handlebars

{{#each shippingMethod in shippingMethods}}
  <div class="field">
    {{ui-radio name="shippingMethod" label=shippingMethod.name value=shippingMethod current=model.shippingMethod}}
  </div>
{{/each}}
````

**Comment by aaronbhansen** [comment]
We use radios in multiple places and as long as value and current are the same object it does select them. Are you sure shippingMethod and model.shippingMethod are both the same object? If they are two different objects or shippingMethod was a string, it wouldn't see it as being equal.

**Comment by aaronbhansen** [comment]
Didn't see any further response, closing.
