### ISSUE TITLE
Deprecation warning when running ember 2.18.0 

### ISSUE THREAD

**Issue by saleswhale-vincent** [Semantic-Org/Semantic-UI-Ember#211]
Running on Ember 2.18.0 gives 

`DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root })`

As per this [comment](https://github.com/ember-cli/ember-cli-version-checker/issues/48#issuecomment-354912902) , the solution is to bump the dependency on ember-cli-version-checker to at least 2.0.0

**Comment by championswimmer** [comment]
we are dropping `ember-promise-tools` soon (that has the sub-dependency that leads to this warning)

**Comment by aaronbhansen** [comment]
If you drop promise tools without replacing it, it will probably be a breaking change for most people as they expect the components to be promise aware at the moment. You'll either need to update promise tools or find an alternative.

**Comment by championswimmer** [comment]
@aaronbhansen 
replaced it with this 

https://github.com/championswimmer/ember-promise-utils 

port of your repository with modern tooling and es6 syntax. uses latest ember-cli-babel so doesn't have deprecation warnings

**Comment by msalahz** [comment]
This deprecation still there due to ember-cli-version-checker@1.3.1 dep for ember-runtime-enumerable-includes-polyfill@2.0.0
```
└─┬ semantic-ui-ember@3.0.0
  └─┬ ember-runtime-enumerable-includes-polyfill@2.0.0
    └── ember-cli-version-checker@1.3.1
```
