### ISSUE TITLE
create a new release with fastboot support

### ISSUE THREAD

**Issue by championswimmer** [Semantic-Org/Semantic-UI-Ember#212]
the latest npm release is 1 year old, and doesn't support fastboot

#master of this repo does work fine with fastboot. we should tag and make a new release

**Comment by aaronbhansen** [comment]
I'm fine if you want to version and create a release

**Comment by championswimmer** [comment]
@niranjan94 
You'd do it ?

**Comment by championswimmer** [comment]
@aaronbhansen 
you can make a 2.1.0 tag on current master 9`9d40e90c8ab586009d22e3da69d78e1199e4c241`)  and publish on npm

(I have even updated the readme to prepare for that)

**Comment by championswimmer** [comment]
done
