### ISSUE TITLE
How to set all items in multi-select dropdown on page refresh

### ISSUE THREAD

**Issue by danr1979** [Semantic-Org/Semantic-UI-Ember#221]
Hi.

Just wondering if someone can help me with an issue I have when using a multi-select dropdown.

Here is a snippet of my template:

`{{#ui-dropdown class="multiple selection" selected=filters.partner onChange=(action (mut filters.partner))}}
                                <i class="dropdown icon"></i>
                                <div class="default text">Select Partner(s)</div>
                                <div class="menu">
                                    {{#each partnerNames as |partnerName|}}
                                        <div data-value="{{partnerName}}" class="item">
                                            {{partnerName}}
                                        </div>
                                    {{/each}}
                                </div>
                            {{/ui-dropdown}}`

When I select items in the dropdown _**filters.partner**_ is being correctly updated with a comma-delimited string of all selected items and the UI is being updated.  However, if I refresh the browser and set _**filters.partner**_ to the previously selected comma-delimited string of items from the route as so:

`let controller = this.controllerFor('applications.elavon.list');
 let filterPartners = params[FILTER_QUERY_PARAM_PARTNER];
 controller.set('filters.partner', filterPartners);`

I find that the multi-select dropdown remains in its default state: nothing selected.

How do I ensure that the comma-delimited values in _**filters.partner**_ result in the dropdown selecting these values and the UI showing this correctly please?

Any help would be appreciated please.

Thank you.

**Comment by khornberg** [comment]
Try providing an array of the values. Something like

      return this.get('filters.partner').split(',').map((id) => {
        return id;
      });

**Comment by danr1979** [comment]
Thanks for your help.
