### ISSUE TITLE
Generate custom ui theme blueprint crashes

### ISSUE THREAD

**Issue by Bouke** [Semantic-Org/Semantic-UI-Ember#223]
When running  `ember generate semantic-ui-custom`, it crashes with the following error message. I'm on ember 3.0 and semantic-ui-ember 3.0.

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'then' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'then' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'then' of undefined
    at Class.afterInstall (C:\Users\Bouke\Developer\yarn-test\node_modules\semantic-ui-ember\blueprints\semantic-ui-custom\index.js:11:53)
    at tryCatcher (C:\Users\Bouke\Developer\yarn-test\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:323:19)
    at invokeCallback (C:\Users\Bouke\Developer\yarn-test\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:495:31)
    at publish (C:\Users\Bouke\Developer\yarn-test\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:481:7)
    at flush (C:\Users\Bouke\Developer\yarn-test\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by championswimmer** [comment]
What is your node version ?

**Comment by Bouke** [comment]
node: 8.9.4
yarn: 1.5.1

**Comment by gibso** [comment]
hey there, 
i got the same issue on ember 3.0, semantic-ui-ember 3.0.0, node 8.10.0 and yarn 1.5.1

**Comment by msalahz** [comment]
same here 
```
ember-cli: 2.18.2
node: 8.10.0
os: darwin x64
```

**Comment by championswimmer** [comment]
@msalahz there is no `semantic-ui-ember` blueprint anymore

**Comment by murat0** [comment]
Same issue here as well when running `ember generate semantic-ui-custom`
Is there any other non hacky way to use the "Packaged Themes" ?

**Comment by jrock2004** [comment]
Same issue here with different versions

```
ember-cli: 3.0.2
node: 9.8.0
os: darwin x64
```

**Comment by jfarlow** [comment]
Additionally, though I can use the old beta3 blueprint generation script to generate the blueprint for a themeable custom semantic-ui, the semantic-ui-less never gets installed, semantic-ui-css never gets removed, and the semantic-ui-ember seems to only reference the -css.

Even manually, is there a way to get the semantic-ui-ember to reference semantic-ui-less rather than -css?

**Comment by championswimmer** [comment]
Sorry for the delay, I'll have time this week to sit and fix this.

**Comment by deanmraz** [comment]
any updates?

**Comment by championswimmer** [comment]
should be gone with 3.0.2

**Comment by Bouke** [comment]
Seeing that this is a recurring issue, would it be possible to document the manual instructions to achieve the same?
