### ISSUE TITLE
Brand & Outline Fonts not being imported into dist

### ISSUE THREAD

**Issue by deanmraz** [Semantic-Org/Semantic-UI-Ember#224]
# Issue 
- Looks like `index.js` does not handle the import of the new brand-* and outline-* 

Line 78-86 

```js 
const importFonts = getDefault('import', 'fonts', [options, defaults])
    if (importFonts) {
      const fontExtensions = ['.eot', '.otf', '.svg', '.ttf', '.woff', '.woff2']
      const sourceFont = getDefault('source', 'fonts', [options, defaults])
      const fontOptions = {destDir: getDefault('destination', 'fonts', [options, defaults])}
      for (let i = fontExtensions.length - 1; i >= 0; i--) {
        app.import(path.join(sourceFont, 'icons' + fontExtensions[i]), fontOptions);
      }
    }
```

Creating this issue for now, will look into creating a PR for this when I get the chance.

**Comment by championswimmer** [comment]
A PR would be awesome !!!!

**Comment by championswimmer** [comment]
Are these part of Semantic UI `2.3` ?

**Comment by deanmraz** [comment]
@championswimmer 
- looks like this change was introduced recently in the 2.3.1 version 
- https://github.com/Semantic-Org/Semantic-UI-CSS/tree/2.3.1/themes/default/assets/fonts

**Comment by championswimmer** [comment]
fixed via https://github.com/Semantic-Org/Semantic-UI-Ember/pull/233
