### ISSUE TITLE
Settings do not take effect

### ISSUE THREAD

**Issue by Bouke** [Semantic-Org/Semantic-UI-Ember#231]
https://github.com/Semantic-Org/Semantic-UI-Ember/blob/2287f49185a591d3674f64b19968afc6714924ac/index.js#L50

I've patched this locally include `(app && app.options['SemanticUI'])`, otherwise the settings as advertised aren't picked up.

```
    const options = (app && app.options['SemanticUI']) || {};
```

Example config:

```
# ember-cli-build.js
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    SemanticUI: {
      import: {
        css: true,
        javascript: false,
        images: false,
        fonts: false
      }
    }
  });
  return app.toTree();
};
```

**Comment by omairvaiyani** [comment]
+1 Just tried a fresh install and ```javascript: false``` is still loading Javascript; we have jQuery disabled so this is a blocking issue

**Comment by championswimmer** [comment]
fixed
