### ISSUE TITLE
Dropdown stays open on `ember-source 3.2.0`

### ISSUE THREAD

**Issue by roschaefer** [Semantic-Org/Semantic-UI-Ember#235]
If I click on a dropdown menu item the `#ui-dropdown` component selects the item but won't close the dropdown menu again.

Downgrading `ember-source` from `3.2.0` to `2.18.2` resolves the issue.

**Comment by roschaefer** [comment]
This seems to be a false positive. We had a conditional css class:
```hbs
{{#ui-dropdown class=(if something 'selection fluid' 'disabled')}}
{/ui-dropdown}}
```
It seems unrelated to this plugin but rather how `ember-source` renders handlebars. This commit resolves the problem for us: https://github.com/roschaefer/rundfunk-mitbestimmen/pull/764/commits/2916d64d8d52cdfb8dd299837827b1ef768bebd0

**Comment by championswimmer** [comment]
Thanks
