### ISSUE TITLE
Guidelines and TODO

### ISSUE THREAD

**Issue by ngouy** [Semantic-Org/Semantic-UI-Ember#246]
Hello, is it possible to have some guidelines or / and TODO things to help maintain this repo ?

It's sad that it's a bit forsaken though I understand maintainers are busy. But If someone wants to catch up and help for example the upgrade to sementic ui 2.3, no idea on how to do that, milestone links ticket that are empty for some of them

Cheers

**Comment by championswimmer** [comment]
Please ask what you'd like to understand, I would love to explain. Yes it has been a bit busy, and unfortunately not working on any Ember project right now.

**Comment by ngouy** [comment]
Thank you for your reply !

what is missing before trying to update to 2.3 ?
Is it "just" that : https://github.com/Semantic-Org/Semantic-UI-Ember/issues?q=is%3Aissue+is%3Aopen+label%3Asemantic-ui%3A2.3

If yes, is it possible to add one or two comments on those issues, like what we need to achieve ?

**Comment by wuarmin** [comment]
@championswimmer what are the todos, which have to be implemented to use latest semantic ui?

**Comment by ngouy** [comment]
@wuarmin I'l be glad to help if you find a way to really get what we can do
