### ISSUE TITLE
Abandoned Framework/Add-On ?

### ISSUE THREAD

**Issue by kushthedude** [Semantic-Org/Semantic-UI-Ember#256]
There have been less to none commits in this repository. Meanwhile, Ember.js release keeps on coming but this framework is not maintained anymore. There have been some discrepancies too with Semantic UI 2.4 release and its ember components. Also, the repository is not maintained with several backlogged issues and PRs.
If there is scope of maintaining it, I can take the initiative forward or if not I request it's maintainers to keep the package going.

**Comment by kushthedude** [comment]
cc: @aaronbhansen @aureliosaraiva

**Comment by aaronbhansen** [comment]
Yes I have stopped maintaining it. Others said they were interested but also haven't done much. If you'd like to maintain it I can add you to the repo.

**Comment by kushthedude** [comment]
> Yes I have stopped maintaining it. Others said they were interested but also haven't done much. If you'd like to maintain it I can add you to the repo.

@aaronbhansen Thanks for quick response. As I personally use Semantic-UI-Ember in my projects. Hence, I think I will do what I can!

**Comment by Panman82** [comment]
FWIW, I plan on looking into [Fomantic UI](https://fomantic-ui.com/), the Semantic UI fork, and might make an ember addon for it (if I end up going down that road). But might wait for their v3, which is to break ties with jQuery and be a bit more framework agnostic.

**Comment by kushthedude** [comment]
Currently there is no work going on for making an Ember add on for Fomantic
UI. Not to mention Fomantic UI has some neat features apart from whivyh
Semanytoc UI offers us. But it is necessary to keep up the Ember Semantic
UI in update with latest features.
Currently, the CI is failing and there are many depreciations

**Comment by aaronbhansen** [comment]
For what its worth you can view this thread. https://github.com/Semantic-Org/Semantic-UI-Ember/issues/195#issuecomment-356998324

I stopped maintaining because we converted everything over to use pure ember to avoid some internal conflicts we were having. It also removed all the Javascript dependencies for semantic which are larger.

**Comment by kushthedude** [comment]
> For what its worth you can view this thread. [#195 (comment)](https://github.com/Semantic-Org/Semantic-UI-Ember/issues/195#issuecomment-356998324)
> 
> I stopped maintaining because we converted everything over to use pure ember to avoid some internal conflicts we were having. It also removed all the Javascript dependencies for semantic which are larger.

I gave it a read but it still misses some of the semantic UI components. We use this library for production deployed applications. And have also faced some issues before like clearable property for drop-down not available in ember and some more. Now with the new release of ember, there have been a lot of deprecation warnings. @aaronbhansen Should this repository be maintained as it is a well-known repo ?

**Comment by aaronbhansen** [comment]
I built a few of the Semantic UI components as the simple semantic repos for our internal use, as we don't use everything in Semantic UI (some Semantic UI components are definitely missing). It was easier to maintain the simple components in ember, vs trying to fix Semantic UIs bugs through this repos wrapping layer. There are definitely some bugs (usually on semantics javascript side), that are harder to fix, and we found we didn't use most of the features of Semantics components anyway, just the basic features.

For this repo maintenance, I've added you as a collaborator and you can maintain it as you'd like. I know people still use it, feel free to update it to help others. I tried to do as little as possible in this code repo and just map ember to Semantic UI, when it was originally built. A lot of the ember components are purely a mixin with a Semantic component name.
