### ISSUE TITLE
Unable to find jQuery Semantic UI module: modal

### ISSUE THREAD

**Issue by iamareebjamal** [Semantic-Org/Semantic-UI-Ember#258]
Error on v3.0.4

https://travis-ci.org/fossasia/open-event-frontend/builds/642460585?utm_source=github_status&utm_medium=notification

**Comment by watermelon-brother** [comment]
I meet the same problem

**Comment by iamareebjamal** [comment]
Add `externals : { jquery: 'jQuery' },` in config
