### ISSUE TITLE
Semantic-UI 2.0

### ISSUE THREAD

**Issue by molligan** [Semantic-Org/Semantic-UI-Ember#26]
Are you planning on supporting the new features that are to be released in semantic-ui 2.0 (specifically multi-select)?

**Comment by aaronbhansen** [comment]
We would like to support all the semantic modules, it's just a matter of when we get time to add them. Our next steps are to probably upgrade ember cli, add tests, and ensure we have support for multiple ember versions. If someone is willing to take multiple select and add tests, that's okay with us too. The base mixin dynamically handles a lot of the semantic modules code, so adding multiple select might be fairly easy.

**Comment by jlukic** [comment]
![s](http://media.giphy.com/media/Tk1RH495RjYYM/giphy.gif)

**Comment by listepo** [comment]
+1

**Comment by esbanarango** [comment]
:+1:

**Comment by jlukic** [comment]
Just wanted to ping that a date has been set, next Tuesday for 2.0

**Comment by aaronbhansen** [comment]
@jlukic Thanks for the update. Ember is also updating to 2.0 at the same time ironically, and so we are working through both that upgrade and adding the 2.0 missing pieces for Semantic UI.

**Comment by jlukic** [comment]
Just curious, does Ember have an exact release date yet?

**Comment by aaronbhansen** [comment]
June 12th was the release of the 2.0 beta. They usually do 6 week iterations on betas. So mid to end of July I imagine they will release it (they don't usually have exact dates). Ember major releases are a little bit different than other frameworks, as most the changes are deprecated code that was removed between the last 1.0 and 2.0 version, verses a huge overhaul on 2.0. So to prepare for 2.0 on Ember, we are just making sure we have all the 1.0 deprecations resolved.

**Comment by jlukic** [comment]
@aaronbhansen 

Launching 2.0 shortly. When its up can you review the integrations guide I've included? Maybe we should include an embedded fiddle or further material. Let me know what you think

**Comment by dopudesign** [comment]
@jlukic - Is Semantic 2.0 going to be used in the Semantic UI Ember 1.0 release? Also, what is the planned date for the Semantic UI Ember 1.0 release?

**Comment by Polve** [comment]
ember 2 has been released :)

**Comment by nathanpalmer** [comment]
Semantic 2 and Ember 2 are both supported with the 0.9.0 release that just went out!
