### ISSUE TITLE
Unknown feature "default-async-observers" found in config/optional-features.json

### ISSUE THREAD

**Issue by ozywuli** [Semantic-Org/Semantic-UI-Ember#261]
```
Unknown feature "default-async-observers" found in config/optional-features.json

An error occurred in the constructor for @ember/optional-features at /Users/<username>/projects/<project_name>/node_modules/semantic-ui-ember/node_modules/@ember/optional-features

An error occurred in the constructor for semantic-ui-ember at /Users/<username>/projects/<project_name>/node_modules/semantic-ui-ember
```

Seeing this error on a fresh install of ember-cli@3.17. Any ideas why?

**Comment by Unkrass** [comment]
I'm having the same issue. I believe that it is not a Semantic-UI-Ember specific issue, but rather Ember-CLI related.

https://guides.emberjs.com/release/configuring-ember/optional-features/#toc_default-async-observers

I opened an issue in the ember-cli repo [here](https://github.com/ember-cli/ember-cli/issues/9226)

**Comment by kulbida** [comment]
Wondering if you were able to find a solution, yet.

**Comment by Unkrass** [comment]
@kulbida unfortunately no. I‘m still waiting for a response in the ember cli repo issue I mentioned in my above comment.

**Comment by Unkrass** [comment]
I have to backpedal. This really is an issue with semantic-ui-ember. When removing the package from package.json it works just fine...

**Comment by Unkrass** [comment]
Okay, so @richard-viney [showed me](https://github.com/ember-cli/ember-cli/issues/9226) that it's an issue with the `@ember/optional-features` dependency inside semantic-ui-ember. So, please someone bump this to 1.3.0.

Until then you can use the following workaround with selective dependency resolutions in package.json (on the same level as dependencies):
````
"resolutions": {
    "semantic-ui-ember/@ember/optional-features": "^1.3.0"
  }
````
For further information on resolutions check https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by richard-viney** [comment]
@Unkrass Could you open a PR that fixes this?

**Comment by Unkrass** [comment]
@richard-viney I have opened a PR

**Comment by palyvodaBoi** [comment]
seems it doesn't work..

**Comment by FrancoisLetourneau** [comment]
There's a PR that was never merged regarding this issue. 

Can we expect a resolution soon?

**Comment by richard-viney** [comment]
My workaround above should continue to work fine. There's not much else to be done except wait for a maintainer to bump the package version and/or merge that small PR.

**Comment by RubenSmit** [comment]
Could this please be resolved? The solution is fine indeed, it only needs to be merged and the version bumped.

**Comment by zubeirtech** [comment]
> Well, @richard-viney just [showed me](https://github.com/ember-cli/ember-cli/issues/9226) that it's an issue with the `@ember/optional-features` dependency inside semantic-ui-ember. So, please someone bump this to 1.3.0.
> 
> Until then you can use the following workaround with selective dependency resolutions in package.json (on the same level as dependencies):
> 
> ```
> "resolutions": {
>   "semantic-ui-ember/@ember/optional-features": "^1.3.0"
> }
> ```
> 
> For further information on resolutions check https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

Thats only working with yarn, for npm please use npm-force-resolutions https://www.npmjs.com/package/npm-force-resolutions
