### ISSUE TITLE
Customise Modal

### ISSUE THREAD

**Issue by joshhornby** [Semantic-Org/Semantic-UI-Ember#27]
Hey,

Using this package is it possible to do some more complex models? Such as the ```allowMultiple```?

http://semantic-ui.com/modules/modal.html#/examples

**Comment by aaronbhansen** [comment]
I don't think so at the moment, mainly because you have to have a named outlet and we are only using one. As we look at redoing the outlet to use components or possibly passing in an outlet name as an option, that might make it possible to do multiple.

**Comment by nathanpalmer** [comment]
We just released the 0.9.0 version of this which changes how modals work. Specifically you can have multiple modals on the same page and you can also control the invoking a bit more (not to mention that all properties are getting proxied to Semantic.) 

You might want to try out some of the other modal scenario's to see how well they work now.

**Comment by aaronbhansen** [comment]
Closing since no acitivity
