### ISSUE TITLE
Icons dont work on animated buttons

### ISSUE THREAD

**Issue by krzkrzkrz** [Semantic-Org/Semantic-UI-Ember#30]
The following doesnt seem to work. The animation works, but no icon displays right after.

    <div class="ui animated button">
      <div class="visible content">Next</div>
      <div class="hidden content">
        <i class="right arrow icon"></i>
      </div>
    </div>

**Comment by aaronbhansen** [comment]
I would imagine this is more related to something on your project setup then this project. We use semantic icons constantly and don't have any issues with them. I'm not sure what to do unless you can replicate this on a jsbin or fresh project. If you can do that, I can look at the differences than what we are doing to see if there needs to be changes to the readme. If you can replicate this we'll reopen the issue.

**Comment by hmaesta** [comment]
For upcoming people with this problem, verify if you don't have any `.hidden` class. 

Here the animated button was not working because of a legacy code from [HTML5 Boilerplate](https://html5boilerplate.com/).
 
```
    /*
     * Hide visually and from screen readers
     */

    .hidden {
        display: none !important;
    }
```

**Comment by speedingdeer** [comment]
had the same thing thanks!

**Comment by ngolforoushan** [comment]
thanks 'hmaesta' your comment was really helpful ;)
