### ISSUE TITLE
Add a disabled to the ui-dropdown component

### ISSUE THREAD

**Issue by bobbysciacchitano** [Semantic-Org/Semantic-UI-Ember#33]
I'm migrating my UI to use Semantic UI and hit a little sticking point with preventing users from selecting an item in a select box. Currently; the select view has a disabled property. Would it be possible to add this as a property to the component rather than a class?

Here is an example of how it could be setup:
```
{{ui-dropdown
    optionValuePath='content.id'
    optionLabelPath='content.label'
    disabled=is_own
    content=roles
    value=model.role
    class='ui selection dropdown'}}
```
Thanks!

**Comment by aaronbhansen** [comment]
Semantic Dropdown has a disabled for the entire dropdown, but not the individual items. In one of our projects we did a custom dropdown item to allow it to have disabled items. Here is a gist of the code:  https://gist.github.com/aaronbhansen/749e4ddf6cc3b89a0328

The semantic ember base mixin is made to override any property that it can find on the component it's mixed into. In the gist, overrode the action method on the dropdown and did the check there. If it wasn't disabled, it executed the 'action activate' method on the dropdown.

Anyway, hopefully that helps.

**Comment by aaronbhansen** [comment]
Closing, as no response

**Comment by jlukic** [comment]
Semantic does have `disabled` on individual items in `2.0`
