### ISSUE TITLE
is there an option to use semantic-ui-ember withough npm or Ember CLI?

### ISSUE THREAD

**Issue by ehudkaldor** [Semantic-Org/Semantic-UI-Ember#4]
just looking to download and include another JS i can use with require.js, to take care of the integration.

**Comment by aaronbhansen** [comment]
We plan to support it, it's just not available yet. Here is a coffeescript gist of the internal source I wrote we are using as the base to convert over to the semantic-ui-ember repository. Everything should work in the gist, and should mirror this repository fairly closely, but the api calls may change as we advance the semantic-ui-ember code base.

https://gist.github.com/aaronbhansen/45732d32ef20fe432053

**Comment by nathanpalmer** [comment]
@ehudkaldor as a curiosity what type of environment are you trying to import it into? Rails? Bower? Nuget?

**Comment by ehudkaldor** [comment]
none. i am but a poor lost circus developer, working alone. i am looking for a js file that i can put in my /packages/ and call it with require.js, to use it. i like Semantic and how it looks, and i am sliding into Ember to see how it feels. there is friction at the seams. specifically, using a Semantic dropdown, and bind it to an Ember model attr, so the value will be set on load and change on change.

**Comment by mfeckie** [comment]
@ehudkaldor Is this still an issue or can this be closed?

**Comment by aaronbhansen** [comment]
We aren't planning to have a non npm or ember cli install anymore.
