### ISSUE TITLE
Use assuming Semantic UI CSS & JS were already loaded

### ISSUE THREAD

**Issue by kalebdf** [Semantic-Org/Semantic-UI-Ember#43]
We would love to use this add-on in our project. However, the addon currently loads and includes the Semantic UI JS and CSS as vendor files through ember-cli. We already have Semantic UI JS and CSS included elsewhere in the project.

Is there a way to exclude the core Semantic UI JS and CSS and only use these wrapper components?

Is there an option to remove them from the Broccoli tree?

Thank you!

**Comment by mfeckie** [comment]
@kalebdf For the use case you describe, I would recommend that you fork the addon and tweak https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/index.js

You can then reference it directly in `package.json` like this

```json
"Semantic-UI-Ember": "git@github.com:your-github/your-repo.git#some-branch",
```

You can then avoid including the JS and CSS by removing the imports.

Having said that, there are *some* risks if the load order isn't exactly right.

You could also look at including Semantic via CDN in the `index.html` across the board..

**Comment by nathanpalmer** [comment]
We just released a version of the library that allows you to disable the auto import of css. You can do this by including a SemanticUI option block and set css to false in the ember-cli-build (or Brocfile)

```
  var app = new EmberApp(defaults, {
    SemanticUI: {
      css: false
    }
  });
```
