### ISSUE TITLE
Questions about Form Validation and Issue with "clear button" ...

### ISSUE THREAD

**Issue by Panoplos** [Semantic-Org/Semantic-UI-Ember#44]
ember.js @ 1.13.1
semantic-ui-ember @ 0.0.1-rc.6

I have the following form code:

```html
<div class="sign-up">
  <h1>
    {{t signUp.header}}
  </h1>
  <form class="ui form">
    <div class="field">
      {{input id="username" name="username" type="text" placeholder=usernamePlaceholder}}
    </div>
    <div class="field">
      {{input name="email" type="text" placeholder=emailPlaceholder}}
    </div>
    <div class="field">
      {{input name="password" type="password" placeholder=passwordPlaceholder}}
    </div>
    <div class="ui blue submit button">Submit</div>
    <div class="ui clear button">Clear</div>
  </form>
</div>
```

However, the `clear` button is not working, as per the Semantic UI Form Validation examples found [here](http://semantic-ui.com/behaviors/form.html).

Also, I have no idea where I would place the actual validation set-up code, like the following:

```js
$('.sign-up form').form({
  fields: {
    name: {
      identifer: 'username',
      rules: [
        {
          type: 'empty',
          prompt: "You must provide a user name!"
        }
      ]
    }
  },
  inline: true,
  on: 'blur'
});
```

Note, if I paste the above into the Chrome console, the validation is not working, still, but somehow the `clear` button starts to work!

Any help with this would be greatly appreciated...

**Comment by aaronbhansen** [comment]
Hi @Panoplos , I haven't actually used semantic validations before. The main reason is it breaks the ember models for handling data and bindings. We use in our own projects, https://github.com/dockyard/ember-validations. The better way would be to have an action on clear that then clears your models data through ember.
```
<div class="ui clear button" {{action "clear"}}>Clear</div>
```
Then in the component or controller something like
```
actions: 
  clear: ->
     @setProperties({
         email: null,
         password: null
     })
```

**Comment by Panoplos** [comment]
OK, I was going to ask what the "best practice" with this was... I like SUI's approach to this, as it is very simple to get the error messages to auto-display.

**Comment by aaronbhansen** [comment]
It is easy, but it breaks the approach on everything being data bound in ember. Data down actions up, if you use semantic validations, you have to then tie into the validations and update the data based on semantics events. For example, when semantic clears the inputs, ember doesn't know they cleared, and so your data doesn't represent the dom, causing a disconnect. Which is why i'm assuming you're seeing the problem.
