### ISSUE TITLE
Dropdown features

### ISSUE THREAD

**Issue by Meph-** [Semantic-Org/Semantic-UI-Ember#47]
Is it possible to use "multiple select"? Or search or images in content? Like examples on page: http://semantic-ui.com/modules/dropdown.html 

I also can't figure optionValuePath. I have always get "model.label" in "selection" variable.

{{ui-dropdown
    content=model
    optionValuePath="content.id"
    optionLabelPath="content.label"
    value=selection
    prompt="Select"
}}

**Comment by listepo** [comment]
See https://github.com/Semantic-Org/Semantic-UI-Ember/pull/46

**Comment by nathanpalmer** [comment]
There is now! We just released version 0.9.0 that works with 2.0 (which has some breaking changes in it.)
