### ISSUE TITLE
Execute action when checkbox value changes

### ISSUE THREAD

**Issue by iamolivinius** [Semantic-Org/Semantic-UI-Ember#50]
I'm looking for a way to execute controller actions whenever i click and change a ui-checkbox component. With the current master branch it's possible to write a template like this:

```hbs
{{ui-checkbox class="toggle"
              checked=reminderIsEnabled
              label=(boolean-to-yesno reminderIsEnabled)
              action="saveSettings"}}
```

While master is not compatible with Ember 2.0 I'm using the prep-1.0 branch where the template above won't run the default action any more. 

Is there another way to declare default actions in the template? I don't want to rely on observers for this case.

**Comment by nathanpalmer** [comment]
You should be able to do this via Semantic's onChange event (only works on the prep-1.0 branch)

See an example in our [dummy app](https://github.com/Semantic-Org/Semantic-UI-Ember/blob/prep-1.0/tests/dummy/app/templates/modules/dropdown.hbs)

```handlebars
{{ui-checkbox class="toggle"
              checked=reminderIsEnabled
              label=(boolean-to-yesno reminderIsEnabled)
              onChange=(action "saveSettings")}}
```

It should sent that action along with the id of the selection for you to handle however you want in the controller.

**Comment by iamolivinius** [comment]
Wouldn't this overwrite the onChange handler here: https://github.com/Semantic-Org/Semantic-UI-Ember/blob/prep-1.0/addon/components/ui-checkbox.js#L8-10

**Comment by nathanpalmer** [comment]
Right, it will override that. Digging in though because it goes a bit deeper.

  1. Doing this will obviously override our onChange handler which means checked won't get set anymore
  2. Semantic is simply setting `this` by using call and that gets overridden by the closure that Ember is creating

The second part we can get around with a small function wrapper. But I'd like to find a good way to preserve both behaviors.

**Comment by nathanpalmer** [comment]
@iamolivinius I've rewritten part of our base action to address both of these. It will no longer overwrite the action and it will also pass through the component so you can grab any corresponding info. You'll need to up in the latest from the prep-1.0 branch

```handlebars
{{ui-checkbox class="toggle"
              checked=reminderIsEnabled
              label=(boolean-to-yesno reminderIsEnabled)
              onChange=(action "saveSettings")}}
```

and then

```javascript
saveSettings: function(component) {
  var value = component.get('value');
}
```

Try it out and see if it works for you.

**Comment by iamolivinius** [comment]
Looks god to me :+1:
