### ISSUE TITLE
prep-1.0: How to set an initial value for ui-dropdown lists?

### ISSUE THREAD

**Issue by iamolivinius** [Semantic-Org/Semantic-UI-Ember#52]
I'm using the ui-dropdown module to display a selection. How can I set a certain entry to be active/selected? In my case `settings.user.currentLanguage` would map to `language.code`.

```hbs
{{#ui-dropdown  class="selection"
                value=settings.user.currentLanguage
                onChange=(action "changeI18nLanguage")}}
  <div class="default text">{{t "settings.language"}}</div>
  <i class="dropdown icon"></i>
  <div class="menu">
  {{#each availableLanguages as |language|}}
    <div class="item" data-value={{language.code}}>
      {{language.name}}
    </div>
  {{/each}}
  </div>
{{/ui-dropdown}}
```

**Comment by nathanpalmer** [comment]
I just added an initialization method onto ui-dropdown that will set the original selection based on the value you pass in (`value=settings.user.currentLanguage` as seen above.)

See 6c8929832c099af6f30a5f95fdbf3f400bd26be1 or just pull down the latest.

**Comment by iamolivinius** [comment]
I see. It's working. Thanks!
