### ISSUE TITLE
prep-1.0: Modal: approve handler does not get called when clicking on button

### ISSUE THREAD

**Issue by iamolivinius** [Semantic-Org/Semantic-UI-Ember#53]
I just cloned the semantic-ui-ember project, checked out the prep-1.0 branch, and run `npm install && bower install && ember serve`.

I selected the menu item modal and clicked and the button "Open Profile", then clicked the green and black button. The modal closes but no alert dialog appears. Guess this is a bug :wink: 

Let me know if u need further information.

**Comment by nathanpalmer** [comment]
Yup, good catch. The the `approve` and `deny` callbacks were removed now that we can simply proxy the functions from semantic itself.

The dummy app was updated to use `onApprove` and `onDeny` in this changeset. e9d319bb6cf3a50565119540d2ed2164d49722c2
