### ISSUE TITLE
Popup/dropdown not working ember 2

### ISSUE THREAD

**Issue by cresg820** [Semantic-Org/Semantic-UI-Ember#55]
Another issue with popup component:
index.hbs
    {{ui-popup content="The text you'd like to show"}}
    {{ui-popup tagName="i" class="icon link" content="The text you'd like to show"}}

If a look into html i get this code
    <div id="ember405" class="ember-view"><h2 id="title">Welcome to Ember</h2>

    <div id="ember427" data-content="The text you'd like to show" class="ember-view"></div>
    <hr>
    <i id="ember428" data-content="The text you'd like to show" class="icon link ember-view"><!---></i>
    </div>

And nothing is visibile.

The same problem with dropdown component

    DEBUG: -------------------------------
    DEBUG: Ember      : 2.0.0
    DEBUG: Ember Data : 2.0.0
    DEBUG: jQuery     : 1.11.3
    DEBUG: -------------------------------
    ember -v
    version: 1.13.8
node: 4.1.1
npm: 2.13.4
os: linux x64

**Comment by cresg820** [comment]
My fail.
I'm using prep-1.0 but I was looking readme of master branch instead of prep-1.0 branch.

But i think there is still one issue with readme of prep-1.0 branch:
* For first popup example you have to include text to show. Like this -> {{#ui-popup content="The text you'd like to show"}}TEXT HERE{{/ui-popup}}
* For second example 'link' icon doesn't exists any more in semantic ui.

**Comment by nathanpalmer** [comment]
Thanks. I commented on the pull request and we can move the conversation there.
