### ISSUE TITLE
How can i change color variables, like @grey ?

### ISSUE THREAD

**Issue by kot-shrodingera** [Semantic-Org/Semantic-UI-Ember#58]

**Comment by kmmathis** [comment]
What I did was followed the build instructions on the Semantic UI website to generate a css file using my color variable overrides. Then I added that css file to my project as a .scss file and imported it in my app.scss

http://semantic-ui.com/introduction/getting-started.html

**Comment by kmmathis** [comment]
And if you do what I did, make sure to specify in your ember-cli-build.js file that you don't want Semantic UI to include its CSS

    /* global require, module */
    var EmberApp = require('ember-cli/lib/broccoli/ember-app');

    module.exports = function(defaults) {
      var app = new EmberApp(defaults, {
        SemanticUI: {
          css: false
        }
      });

      // blah blah blah

      return app.toTree();
    };

**Comment by kot-shrodingera** [comment]
CSS is generated only after building Semantic-UI with gulp? Is it possible to rebuild semantic ui while rebuilding Ember app?

**Comment by kmmathis** [comment]
I tried it that way first, following this repo as an example: https://github.com/nathanpalmer/example-semantic-ui-ember-cli

The build times were just too long for it to be useable, so I decided to do a one-time build with gulp to keep things quick. There might be a way to speed it up but I haven't spent any time trying to figure that out.

**Comment by kot-shrodingera** [comment]
Thanks, that was exactly what i wanted to know
