### ISSUE TITLE
Support for dropdown using selection option

### ISSUE THREAD

**Issue by slightlytyler** [Semantic-Org/Semantic-UI-Ember#6]
Hey there, really interested in this project as I'm currently using Semantic on a project and have implemented many of these components on my own. Definitely interested in contributing to this project in the future.

Anyway, one of the components I have the most problems with is `ui-dropdown` specifically when trying to bind to objects rather than values by using the `selection` option rather than `value`. Do you have any support for this or a method of working around it?

**Comment by nathanpalmer** [comment]
This should be working today. Here is an example from our codebase where we set a custom label but the value is the object itself.

```
{{ui-dropdown
    prompt="Select a Product" 
    content=project.products 
    value=product 
    optionLabelPath="content.name" 
    classNames="fluid"}}
```

**Comment by slightlytyler** [comment]
@nathanpalmer just tested and it works!
