### ISSUE TITLE
Full Assets with no URLs

### ISSUE THREAD

**Issue by jpserrett** [Semantic-Org/Semantic-UI-Ember#60]
I am building an Ember app and would like to use Semantic UI. However, I cannot have external access to URLs. It will be on a closed off system that will need to have everything it needs locally in order to work, so the links to things like 'fonts.gstatic.com', for instance, won't work. 

Is there a way to download a complete package of Semantic UI somewhere? If not, is there a way to quickly update it so that I can use it without needing those external URLs? 

Thanks!

**Comment by nathanpalmer** [comment]
Closing this out since it looks like you received an answer in the [Semantic-UI issues](https://github.com/Semantic-Org/Semantic-UI/issues/3223) thread. Hopefully you were able to work it out.
