### ISSUE TITLE
How to run the test/dummy app

### ISSUE THREAD

**Issue by meekazhu** [Semantic-Org/Semantic-UI-Ember#63]
When I install the addon and I copy test/dummy/app into my ember project, I can't get it to run. Is there any steps that I need to do to run the test app directly within the addon.

Thanks,

**Comment by listepo** [comment]
@minmin138 dummy app running in addon folder ```ember server``` see ```http://localhost:4200```

**Comment by minmin138** [comment]
wait these files aren't the same as the one generated from doing bower install semantic-ui-ember ? I thought they were the same project, just checked the git log.

**Comment by aaronbhansen** [comment]
I don't think we updated the dummy app in the refactor. That was created when the project first started

**Comment by nathanpalmer** [comment]
The dummy app was partially updated during the refactor but I'm sure is still a little out of date. I have no idea how well copying it into a new project would work though. You can checkout the semantic-ui-ember project and just run `ember server` as @listepo mentioned and it should come up.
