### ISSUE TITLE
Don't work with Bootstrap

### ISSUE THREAD

**Issue by kot-shrodingera** [Semantic-Org/Semantic-UI-Ember#66]
After I installed Bootstrap via bower and imported less and js files, semantic-ui component like dropdown aren't working, throwing Uncaught TypeError: Cannot read property 'call' of undefined [bootstrap.js:880]
When i bower install semantic-ui and import semantic css and js everything's working

**Comment by aaronbhansen** [comment]
We aren't planning to support bootstrap and semantic UI in the same project. If you find out why its not working and want to submit a pull request, feel free too and we'll look it over.
