### ISSUE TITLE
Two way sync of dropdown value

### ISSUE THREAD

**Issue by brendan-rius** [Semantic-Org/Semantic-UI-Ember#70]
If I have a dropdown like

```
{{#ui-dropdown class="selection" onChange=(action 'change') value=variable}}
// something
{{/ui-dropdown}}
```

changing `variable` changes dropdown's value internally, but the does not update the display

**Comment by nathanpalmer** [comment]
Hey @brendan-rius. The problem here is that we should be binding to selected instead of value. According to the semantic documentation setting value does not update the display. We just rolled out a new release that makes that part more clear.
