### ISSUE TITLE
Modal approval click closes modal but doesn't trigger callback

### ISSUE THREAD

**Issue by radcliff** [Semantic-Org/Semantic-UI-Ember#73]
The following set up doesn't seem to work for me. I have a `ui-modal` like:

```
{{#ui-modal name="update" class="basic" onApprove=( action "update")}}
  // ...
  <div class="actions">
    <div class="ui approve button">OK</div>
  </div>
{{/ui-modal}}
```
and the action set as well:
```
UpdateComponent = Ember.Component.extend
  actions:
      update: () ->
        alert('updated')
```

Clicking the `OK` approval button closes the modal, but the alert is never fired. I am using the `prep-1.0` branch and changed from `approve` to `onApprove` but can't get this to work.

**Comment by nathanpalmer** [comment]
Hey @radcliff. Can you try this against the most recent release? `prep-1.0` was merged into master and is a little bit outdated. We do have an [approve action test](https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/tests/integration/components/ui-modal-test.js#L44) as well so if you're still getting the problem it would be great if you could create a test that identifies it.

**Comment by nathanpalmer** [comment]
Hey @radcliff. Closing this out for now. If you are able to test it against master (or our latest release on npm) I'd be happy to re-open.
