### ISSUE TITLE
Ember 2.3 "Uncaught TypeError"

### ISSUE THREAD

**Issue by Panman8201** [Semantic-Org/Semantic-UI-Ember#78]
Running into an error when trying to use this with ember 2.3.0-beta.1, ember-cli 2.2.0-beta.1, and jquery 2.1.4. The Chrome error is "Uncaught TypeError: Can't add property DEBUG, object is not extensible" coming from the `// Static properties to ignore` code in the [base Mixin](https://github.com/Semantic-Org/Semantic-UI-Ember/blob/v0.9.2/addon/mixins/base.js#L126-L128).

**Comment by Panman8201** [comment]
Is there a reason the static properties are on the `Semantic.BaseMixin` rather than the `Semantic` Namespace itself? I've tried a couple different solutions to no avail.

**Comment by avaz** [comment]
I'm facing the same issue.

**Comment by Panman8201** [comment]
@avaz For now I've manually modified that file to move the properties onto the Mixin itself, but I'm sure there is a better way. Here is the base mixin with my modifications: https://gist.github.com/Panman8201/c9ebf301bab3048e5e35 

The specific changes are;

1. [Comment out the existing properties](https://gist.github.com/Panman8201/c9ebf301bab3048e5e35#file-base-js-L131-L133)
2. [Add the properties to the mixin itself](https://gist.github.com/Panman8201/c9ebf301bab3048e5e35#file-base-js-L124-L127)
3. Change the usage in the mixin; [DEBUG](https://gist.github.com/Panman8201/c9ebf301bab3048e5e35#file-base-js-L29), [STANDARD](https://gist.github.com/Panman8201/c9ebf301bab3048e5e35#file-base-js-L33), [EMBER](https://gist.github.com/Panman8201/c9ebf301bab3048e5e35#file-base-js-L41)

File location in your project is `node_modules/semantic-ui-ember/addon/mixins/base.js` Note, you'll need to modify that file every time the addon is installed or re-installed (until a fix is release).

**Comment by avaz** [comment]
@Panman8201 thanks, it fix the problem. 
I'm curious, which change in ember 2.3.x that causa this properties to become read only, do you know?

**Comment by Panman8201** [comment]
@avaz I tried looking for what changed but never found the source. It's something with the Mixin class though, since that's what `Semantic.BaseMixin` is...

https://github.com/emberjs/ember.js/compare/v2.2.0...v2.3.0-beta.3#diff-109

**Comment by nathanpalmer** [comment]
Hey guys. I just made a minor change to how we using DEBUG, STANDARD AND EMBER in the the `78-base-mixin-beta` branch. It gets things working again in 2.3.0 beta. Try it out if you'd like. I haven't done a ton of testing on this version of Ember so it would be great to get some feedback on it before we merge it in.

**Comment by Panman8201** [comment]
@nathanpalmer the `78-base-mixin-beta` branch works for me, thanks! As for feedback; `const` seems more appropriate than `var` (but technically not needed) and you could `export` them for use in other files (not sure how useful that would be in this case). So basically, replace the `var`'s with `export const`. I'm using this approach elsewhere in an app, per recommendation from the greater ember community.

**Comment by avaz** [comment]
@nathanpalmer the branch worked for me too!
