### ISSUE TITLE
Dropdown Items not Clickable

### ISSUE THREAD

**Issue by CrshOverride** [Semantic-Org/Semantic-UI-Ember#8]
When using `ui-dropdown`, the elements in the dropdown are not clickable.

After debugging, it looks like this is caused by the fact that the `content` for the dropdown is being set inside the `then` block of a promise. The Semantic component is only being initialized by `BaseMixin.didInsertElement` which doesn't fire in this case.

**Comment by aaronbhansen** [comment]
Thanks, that fixed the issue when content was updated.
