### ISSUE TITLE
Are all module callbacks exposed?

### ISSUE THREAD

**Issue by Panman8201** [Semantic-Org/Semantic-UI-Ember#81]
I've seen a couple examples in the readme where the module callback was exposed for parent actions. Is this the case for *all* module callbacks? If not, it would be nice if they were. Ex:

```hbs
{{ui-modal name="foobar" onHide=(action "hidingModal")}}
```

**Comment by nathanpalmer** [comment]
Yes ALL callbacks are exposed. The components themselves wrap thinly over semantic and pass everything you throw in as a property to semantic. If that ends up being an action it should proxy a function through!
