### ISSUE TITLE
Dropdown get selected object

### ISSUE THREAD

**Issue by denchen** [Semantic-Org/Semantic-UI-Ember#84]
In the notes for pull #46 , it offers a way to bind to an object for a dropdown. But how do I get the object selected? For instance, if I have this template:

```
{{#ui-dropdown class="fluid selection dropdown" selected=selectedOption}}
    <i class="dropdown icon"></i>
    <span class="default text">Select something</span>
    <div class="menu">
        {{#each items as |item|}}
        {{#ui-dropdown-item content=item}}
            {{item.name}}
        {{/ui-dropdown-item}}
        {{/each}}
    </div>
{{/ui-dropdown}}
```

And in my controller I have:

```
items: [{ id: 0, name: 'AAA' }, { id: 1, name: 'BBB' }, { id: 2, name: 'CCC' }],
heardSelected: function () {
    var selectedOption = this.get('selectedOption');
    console.log('Heard dropdown change:');
    console.log('selectedOption');
    console.log('id: ' + selectedOption.id);
    console.log('name: ' + selectedOption.name);
    console.log('properties: ' + selectedOption.keys());
}.observes('selectedOption');
```

When I select an item from the dropdown, this is what I see in the console:

```
selected: 
Heard dropdown change: 
application.js:26 [object Object]
application.js:27 id: undefined
application.js:28 name: undefined
application.js:29 Uncaught TypeError: selectedOption.keys is not a function
```

**Comment by nathanpalmer** [comment]
You might be running into an issue with newer versions of Semantic-UI that won't store complex data in the .data() property anymore on the element. See [here](https://github.com/Semantic-Org/Semantic-UI/issues/3293) for more information.

We've solved this on other projects by introducing a `ui-dropdown-array` wrapper that will perform it's own lookups on the array.

```handlebars
{{#ui-dropdown-array class="fluid selection" content=pricing_plans selected=company.pricing_plan}}
  <input type="hidden" name="source" value={{company.pricing_plan.id}}>
  <i class="dropdown icon"></i>
  {{#if company.pricing_plan}}
  <div class="default text">{{company.pricing_plan.name}}</div>
  {{/if}}
  <div class="menu">
  {{#each pricing_plans as |content|}}
    <div class="item" data-value={{content.id}}>{{content.name}}</div>
  {{/each}}
  </div>
{{/ui-dropdown-array}}
```

That of course is not part of this library just yet but sounds like we should pull it in.

**Comment by denchen** [comment]
Yeah, this is something I would like, in part because I'm using data pulled in from `this.store.findAll()`, and each item has other properties I'd like to access if selected. The workaround I have is to create a standard ui-dropdown with `data-value` keyed on `item.id` and then once selected do a lookup of `id` in our original model. Not ideal, but it works.

**Comment by aaronbhansen** [comment]
We recently merged in the the ui-dropdown-array branch. We'll be releasing a version in the next week on npm. I'm going to close this issue for now, if you have any problems with dropdown array, please open another issue.

**Comment by DidelotK** [comment]
The ui-dropdown-array doesn't exist anymore, how can i have the same result on 2.0.0 ?
