### ISSUE TITLE
Bug for setting multi-select dropdown defaults?

### ISSUE THREAD

**Issue by denchen** [Semantic-Org/Semantic-UI-Ember#85]
I'm trying to set defaults for multi-select. The code I have is here:

```
{{#ui-dropdown class="multiple select" selected=selectedOptions}}
    <div class="default text">Select options</div>
    <i class="dropdown icon"></i>
    <div class="menu">
        {{#each options as |item|}}
        <div class="item" data-value={{item.id}}>
            {{item.name}}
        </div>
        {{/each}}
    </div>
{{/ui-dropdown}}
```

If I pass in `selectedOptions` with just a single option, say `id1`, then `id1` will be selected by default, as expected. But if I pass in `id1,id2`, then it doesn't work and nothing is selected by default. However, if I instead initialize the dropdown via:

```
{{#ui-dropdown class="multiple select" value=selectedOptions}}
```

Then passing in `id1,id2` DOES work and both options are selected by default. However, from perusing the documentation, from my understanding, we should be binding to `select` and not `value`. So is this a bug of some sort?

**Comment by nathanpalmer** [comment]
Hmm. Yeah I don't see anything particularly wrong with what you posted. We use the multiple and it pre-populates as it should. Here is an example. The only thing that looks like is different is the hidden input field.

```handlebars
{{#ui-dropdown class="fluid multiple selection" selected=source}}
  <input type="hidden" name="source" value={{source}}>
  <i class="dropdown icon"></i>
  <div class="default text">Any Source</div>
  <div class="menu">
  {{#each source_options as |option|}}
    <div class="item" data-value={{option.id}}>{{option.title}}</div>
  {{/each}}
  </div>
{{/ui-dropdown}}
```

**Comment by denchen** [comment]
Thank you. Adding `<input type="hidden" name="source" value={{source}}>` worked perfectly. My question is, is this actually documented anywhere, because I was unable to find it? Is this something I should add to all my dropdowns that require default values?

**Comment by aaronbhansen** [comment]
In a few of the semantic dropdown examples it shows the input in the markup, but I don't know if it is specifically called out. The reason why it might not be in the documentation is Semantic actually adds some additional element items to your dropdown (and other semantic modules), when its initialized. If you create a new semantic dropdown and the input isn't there, it append it to the DOM for you. This can be a problem when you are binding in ember. If you want to create a pull request expanding the read.me that would be great.
