### ISSUE TITLE
What happened to `modal` mixin?

### ISSUE THREAD

**Issue by EhsanYousefi** [Semantic-Org/Semantic-UI-Ember#89]
What happened to `modal` mixing? I wanted to open an external modal by `this.send('openModal', 'modal_path');` but I couldn't. What's the new solution?

**Comment by aaronbhansen** [comment]
It was removed as we are trying to find the best way to display modals with a minimal about of work. If you look at this branch, it has some modal options you can use https://github.com/unchartedcode/semantic-ui-ember-modal. Also look at this comment for some additional examples https://github.com/Semantic-Org/Semantic-UI-Ember/issues/83#issuecomment-174064620. We are hoping to have a better modal implementation in our next major release.
