### ISSUE TITLE
Radio only works by clicking

### ISSUE THREAD

**Issue by ivanbanov** [Semantic-Org/Semantic-UI-Ember#90]
When using the radio component 

```
{{ ui-radio label="foo" name="test" value="foo" current=model.radio }}
{{ ui-radio label="bar" name="test" value="bar" current=model.radio }}
```

if you click in the radios the value of `model.radio` changes, but if you try to navigate between the radios using the keyboard it doesnt affect the `model.radio` getting the model and UI not synced :disappointed:

**Comment by aaronbhansen** [comment]
You want to try [this branch](https://github.com/Semantic-Org/Semantic-UI-Ember/tree/use-component-lifecycle) and see if it fixes your issue. It would also be good to add a unit test for it, if you can create it in a pull request on that branch.

**Comment by aaronbhansen** [comment]
Branch was merged in and fixed this issue
