### ISSUE TITLE
How to use Sidebar with Ember 2 components

### ISSUE THREAD

**Issue by xtagon** [Semantic-Org/Semantic-UI-Ember#92]
Hi,

Your Sidebar documentation instructs to create an application component/view. However, I am unaware of how to create an application component (if that's possible in Ember 2) and views are deprecated.

By following the rest of the instructions, the sidebar now works. However, the these errors come up in the console:

- `Sidebar: Had to add pusher element. For optimal performance make sure body content is inside a pusher element`
- `Sidebar: Had to move sidebar. For optimal performance make sure sidebar and pusher are direct children of your body tag`

I have a pusher element, but I don't know how I can create an application view/component in Ember 2, so what's the supported way to get this to work?

Thanks so much,

Justin

**Comment by gvsro** [comment]
+1. Even if you generate a component they appear in the `{{content-for "body-footer"}}` (from the index.html). What is the proper way to do it?

**Comment by Beck89** [comment]
+1 I've spent a few hours looking for a solution to get rid of this error but no luck.

**Comment by raldur** [comment]
+1 Anyone found a solution?

**Comment by aaronbhansen** [comment]
I believe all you need to have is a pusher element adjacent to the sidebar component. If you look at the dummy applications sidebar [template](https://github.com/Semantic-Org/Semantic-UI-Ember/blob/use-component-lifecycle/tests/dummy/app/templates/application.hbs) and then how it's triggered in the [controller](https://github.com/Semantic-Org/Semantic-UI-Ember/blob/use-component-lifecycle/tests/dummy/app/controllers/modules/sidebar.js), that should provide an example of one way to do it. That help answer your question?

**Comment by Panman8201** [comment]
@aaronbhansen That will still modify the DOM outside of Ember's control (which can cause problems). http://semantic-ui.com/modules/sidebar.html#page-structure

> Sidebar will automatically add the correct layout on first load if it is not set-up, however fixing your page's layout on load will reduce performance and is not recommended.

The solution is to specifically set the `context`: http://semantic-ui.com/modules/sidebar.html#using-a-custom-context However, I can't seem to get the `{{ui-sidebar}}` component to pickup my custom context. If I make my own component and initialize it with the context it seems to work. Thoughts? This works:

```javascript
// app/components/my-ui-sidebar.js
import Ember from 'ember';
export default Ember.Component.extend({
    didInsertElement() {
        let $rootView = Ember.$('body.ember-application > div.ember-view');
        $rootView.addClass('pushable');
        this.$().sidebar({
            context: $rootView
        }).sidebar('attach events', `#${this.get('elementId')} .item`);
    }
});
```

```hbs
{{!-- app/templates/application.hbs --}}
{{#my-ui-sidebar class="ui inverted labeled icon left inline vertical sidebar menu"}}
    <a class="item">
      <i class="home icon"></i>
      Home
    </a>
    <a class="item">
      <i class="block layout icon"></i>
      Topics
    </a>
    <a class="item">
      <i class="smile icon"></i>
      Friends
    </a>
    <a class="item">
      <i class="calendar icon"></i>
      History
    </a>
{{/my-ui-sidebar}}

{{!-- Note the need to add a background color here.. --}}
<div class="pusher" style="background-color:white">
	<h2 id="title">Welcome to Ember</h2>
	<button {{action "toggleSidebar"}}>Toggle Sidebar</button>
	{{outlet}}
</div>
```

**Comment by aaronbhansen** [comment]
If you look at [base mixin](https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/addon/mixins/base.js#L7), there are a few reserved words we had to work around originally (might not be a problem any more with this.attrs, but we need to look at it more). Context is one of those words thats found on the ember component by default and on semantic in a few cases. Because we are binding semantic automatically to whatever properties are found on the component, we had to create a black list of items to ignore. With that said there is a work around, if you pass any properties in with ui_{name} or ui_context in this situation to the component, it will pass those properly to semantic. You only need to prefix ui_ on the specific blacklisted words, everything else works fine. 
Your code just needs to change to 
```{{ui-sidebar ui_context=context}}```

**Comment by Panman8201** [comment]
@aaronbhansen Indeed! So, the "solution" I'm going with is to extend the `{{ui-sidebar}}` component with:

```js
// app/components/ui-sidebar.js
import Ember from 'ember';
import UiSidebar from 'semantic-ui-ember/components/ui-sidebar';

export default UiSidebar.extend({
  ui_context: 'body.ember-application > div.ember-view',
  didInsertElement() {
    Ember.$( this.get('ui_context') ).addClass('pushable');
    this._super( ...arguments );
    this.$().sidebar('attach events', `#${this.get('elementId')} .item`);
  }
});
```

```hbs
{{!-- app/templates/application.hbs --}}
{{#ui-sidebar class="inverted labeled icon left inline vertical menu"}}
  <a class="item">
    <i class="home icon"></i>
    Home
  </a>
  ...
{{/ui-sidebar}}
<div class="pusher" style="background-color:white">
  <h2 id="title">Welcome to Ember</h2>
  {{outlet}}
</div>
```

Is the "attach events" mentioned in the docs important enough to add special logic for? I could submit a PR if you'd like. Also could include this way of handling the sidebar in the README.md

**Comment by aaronbhansen** [comment]
That works for now, we are actually looking to expose a composable action in version 2 that would be passed into the block for this exact situation. It would look something like this:

```
{{#ui-sidebar as |execute|}}
   <a class="item" {{action (execute "hide)}}>
```

That would expose a way to directly interact with semantic without having to extend the existing component. You could call one of the behavior methods from that execute action directly.

One thing you could do if you wanted, execute exists today just not as an action. You could replace this line:
```this.$().sidebar('attach events', `#${this.get('elementId')} .item`);```
with
```this.execute('attach events', `#${this.get('elementId')} .item`);```

It lets you invoke any call without knowing the semantic module names.

**Comment by aaronbhansen** [comment]
I also updated the unit tests and readme in my branch to show how to do this for future reference.

```
test('it renders', function(assert) {
  this.render(hbs`
    <div class="component context">
      {{#ui-sidebar ui_context=".component.context"}}
        <a class="item">1</a>
        <a class="item">2</a>
        <a class="item">3</a>
      {{/ui-sidebar}}
      <div class="pusher">
        Main Content here
      </div>
    </div>
  `);

  assert.equal(this.$('.ui.sidebar').length, 1);
  assert.equal(this.$('.ui.sidebar a').length, 3);
});
```

**Comment by xtagon** [comment]
Hi everyone, thank you for the replies.

I tried @aaronbhansen's solution and it did make the errors go away, but also had the unintended result of making the sidebar not animate. With your fix applied, opening or closing the sidebar animates only the pusher and not the menu. The push slides in/out, but the menu instantly shows/hides with no transition. It looks very quirky and I'm not sure why it's happening. Any ideas?

**Comment by aaronbhansen** [comment]
If you look at the [examples page](http://semantic-ui.com/modules/sidebar.html#/examples), you need to have the context be a segment class and pushable. The example used is:

```
<div class="ui segment pushable">
  <div class="ui inverted labeled icon left inline vertical sidebar menu">
    ....
  </div>
  <div class="pusher">
    ...
  </div>
</div>

**Comment by xtagon** [comment]
@aaronbhansen When I make the context class "ui segment pushable" instead of just "pushable", it fixes the opening/closing glitch but now my entire page has unwanted margins/padding/border due to the segment class. The styling was fine without the "segment" class. Any more suggestions?

By the way I really appreciate your help and everyone else's help here. :+1:

**Comment by xtagon** [comment]
I ended up just using `ui attached segment pushable` and removing the border style myself. Thanks everyone!

**Comment by kevintraver** [comment]
This works great, but the context scrolls with the app.

Is there a way to have the main content locked, and scroll only the sidebar while it's activated?

**Comment by aaronbhansen** [comment]
Sounds more like a css issue @kevintraver, Something like fixing the sidebar or absolute position. If you look at the Semantic-UI docs site, thats how its done. 

![image](https://cl.ly/2S0G0k0U3D0n/Screen%20Shot%202016-08-15%20at%2010.21.22%20PM.png)
