### ISSUE TITLE
How to set options like closable on modal

### ISSUE THREAD

**Issue by suffle** [Semantic-Org/Semantic-UI-Ember#93]
I try to set my modal to closeable=false. But as soon as U use some options on a modal like 	`Ember.$('.ui.modal').modal({
				closable: false
			}).modal('show');
		`

my modal opens just once, The second time I click the button, nothing happens, even if I leave the option itself out (`Ember.$('.ui.modal').modal().modal('show')`).

 Without options (`Ember.$('.ui.modal').modal('show');`) everything works fine and the modal opens every time i click the button.

**Comment by aaronbhansen** [comment]
Its hard to say without seeing more. You aren't actually doing anything related to ember, just calling jquery and opening a modal. You can look at this comment for doing it more in an ember fashion https://github.com/Semantic-Org/Semantic-UI-Ember/issues/83#issuecomment-174064620. If you want to do it through jquery, I'd recommend opening a semantic-ui issue instead.
